<div align="center"><span style="font-family: Arial,Helvetica,sans-serif; color:#0000FF""><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2021/22</span>
    <br>
    Facultad de Ciencias de la Universidad de Málaga
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. María López y Francisco José Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="color:#FF0000">Práctica número 9</span>
    </b></span></div>

In [1]:
from algoritmos import *

El objetivo de esta práctica es desarrollar programas <span style="font-family: Courier,monospace">Python</span> para calcular autovalores y autovectores de matrices mediante el <span style="color:#FF0000"><b>método de la potencia</b></span> y sus <span style="color:#FF0000"><b>variantes</b></span>.

Recordamos que el algoritmo del <b>método de la potencia</b> para calcular el <b>autovalor dominante</b>, y la <b>dirección de un autovector</b> asociado al mismo, de una matriz $A\in\mathcal{M}_n(\mathbb{K})$, se basa en calcular una sucesión de vectores unitarios (para una cierta norma) $\{X_k\}_{k\in\mathbb{N}}$ y $n$ sucesiones numéricas $\{\lambda^j_k\}_{k\in\mathbb{N}}$ mediante el siguiente algoritmo:
<ul>
<li> dado $X_0\in\mathbb{C}^n-\{0\}$ unitario;</li>
<li> para $k=0,1,2,\ldots$, se contruye
    
$$
Y_{k+1} = A\,X_k \quad y \quad X_{k+1} = \frac{1}{\|Y_{k+1}\|}\,Y_{k+1}\,;
$$
igualmente, siempre que tengan sentido, se calculan

$$
\lambda^j_{k+1} = \frac{(Y_{k+1})_j}{(X_k)_j}\,, \quad j=1,2,\ldots, n\,.
$$

</li>

</ul>
Sabemos también que bajo ciertas hipótesis (autovalor $\lambda_1$ dominante único, excepto multiplicidad, buena elección del vector inicial, etc.) se obtienen resultados de convergencia en el siguiente sentido:
<ul>
    <li>se tiene la convergencia de normas
$$
\lim_{k\to\infty} \|Y_{k+1}\| = \lim_{k\to\infty} \|A\,X_k\| = |\lambda_1|\,;
$$
</li>
    <li>se tiene la convergencia del cociente de componentes (cuando tengan sentido)
$$
\lim_{k\to\infty} \lambda^j_k = \lim_{k\to\infty} \frac{(Y_{k+1})_j}{(X_k)_j} = \lambda_1\,, \quad j=1,2,\ldots, n\,;
$$
</li>
    <li>se tiene la convergencia de los vectores
$$
\lim_{k\to\infty} \left( \frac{\bar{\lambda}_1}{|\lambda_1|} \right)^k X_k
$$
hacia un autovector asociado al autovalor $\lambda_1$.</li>
</ul>


Elaboramos a continuación un programa que implementa el algoritmo del método de la potencia. Dicho programa, de nombre <span style="font-family: Courier,monospace">potencia()</span>, tiene como argumentos de entrada, por este orden, la matriz <span style="font-family: Courier,monospace">A</span>, el vector inicial con el que comenzar las iteraciones <span style="font-family: Courier,monospace">X</span>, la norma <span style="font-family: Courier,monospace">norma</span> con la que realizar el proceso de normalización, el número máximo de iteraciones <span style="font-family: Courier,monospace">itermax</span> superadas las cuales el proceso se detendrá, y la tolerancia <span style="font-family: Courier,monospace">tol</span> que establece el test de parada. En caso de éxito, los parámtros de salida son una variable booleana indicando que efectivamente se ha alcanzado una situación de convergencia (en caso contrario se envía un mensaje explicativo de error), así como los últimos valores calculados de la sucesión de las normas de $Y_k$, de las sucesiones $\lambda^j_k$, $j=1,2,\ldots,n$ y de los vectores $X_k$.
<br>
En el algoritmo implementado se realizarán iteraciones mientras que el número de iteraciones sea inferior al máximo establecido dado y el error sea superior o igual a la tolerancia dada, calculándose el error sobre el valor absoluto de la diferencia de las normas de $Y_{k+1}$ e $Y_k$. En un primer momento podemos hacer que el programa imprima bastante información durante las iteraciones; una vez que se conozca el funcionamiento del mismo, puede ser interesante imprimir menos información.


In [5]:
def potencia(A, X, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n != r or s != 1:
        return False, 'ERROR potencia: no se ejecuta el programa.'
    k = 0
    error = 1.
    normaold = 0.
    lambdas = zeros(n, dtype=complex)
    while k < itermax and error >= tol:
        k = k+1
        Y = A@X
        normanew = norm(Y, norma)
        error = abs(normanew - normaold)
        for i in range(n):
            if abs(X[i, 0]) >= 1.e-100:
                lambdas[i] = Y[i, 0]/X[i, 0]
            else:
                lambdas[i] = 0.
        X = Y/normanew
        print('Iteración: k = ', k)
        print('Norma: ||A*X_k|| = ', normanew)
#        print('Lambdas: lambdas_k = \n', lambdas)
#        print('Vectores: X_k = \n', X)
        normaold = normanew
    if k == itermax and error >= tol:
        return False, 'ERROR potencia: no se alcanza convergencia.'
    else:
        print('\n Potencia: convergencia numérica alcanzada.')
        return True, normanew, lambdas, X


<span style="color:#FF0000"><b>Ejercicio 1.</b></span> Dada la matriz
$$
A = \left( \begin{array}{rrrr} -2 & 3 & -3 & 11 \\ -8 & 9 & -12 & 20 \\ -3 & 3 & -6 & 15 \\ -3 & 3 & -3 & 12 \end{array} \right)\,,
$$
calcular mediante el método de la potencia, si es posible, su autovalor dominante y un autovector asociado. Utilizar la norma infinito y tomar como vector inicial el primer vector de la base canónica de $\mathbb{C}^4$.

In [2]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = \n", A)
X0 = array([[1], [0], [0], [0]])
print("X_0 = \n", X0)
exito, normaY, lambdas, X = potencia(A,X0,inf,200,1e-10)
if exito:
    print("Valor de las normas: ", normaY)
    print("Valores de los lambdas: ", lambdas)
    print("Autovector: ", X)
else:
    print("Error no convergencia")

A = 
 [[ -2   3  -3  11]
 [ -8   9 -12  20]
 [ -3   3  -6  15]
 [ -3   3  -3  12]]
X_0 = 
 [[1]
 [0]
 [0]
 [0]]

 Potencia: convergencia numérica alcanzada.
Valor de las normas:  9.000000000003144
Valores de los lambdas:  [9.01549431+0.j 9.        +0.j 9.01549431+0.j 9.01549431+0.j]
Autovector:  [[-0.99657451]
 [-1.        ]
 [-0.99657451]
 [-0.99657451]]



Una variante del método de la potencia es el <b>método de la potencia inversa</b>, que consiste en aplicar el método de la potencia a la matriz $A^{-1}$, en caso de que la misma exista (en caso contrario significa que es singular, y por tanto $\lambda=0$ es autovalor).
<br>
Elaboramos a continuación un programa, de nombre <span style="font-family: Courier,monospace">potenciainv()</span>, con los mismos parámetros de entrada y de salida que el anterior, que implemente dicho algoritmo.
<br>
Notamos que en la implementación utilizaremos el método $L\,U$ para calcular la solución de $Y_{k+1}=A^{-1}\,X_k$, por lo que habría que hacer una única llamada al principio al programa <span style="font-family: Courier,monospace">facto_lu()</span> y llamadas a los programas <span style="font-family: Courier,monospace">descenso1()</span> y <span style="font-family: Courier,monospace">remonte</span> en cada iteración.


In [3]:
def potenciainv(A, X, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n != r or s != 1:
        return False, 'ERROR potencia: no se ejecuta el programa.'
    exito, LU = facto_lu(A)
    k = 0
    error = 1.
    normaold = 0.
    lambdas = zeros(n, dtype=complex)
    while k < itermax and error >= tol:
        k = k+1
        exito, Y = descenso1(LU,X)
        exito, Y = remonte(LU, Y)
        normanew = norm(Y, norma)
        error = abs(normanew - normaold)
        for i in range(n):
            if abs(X[i, 0]) >= 1.e-100:
                lambdas[i] = Y[i, 0]/X[i, 0]
            else:
                lambdas[i] = 0.
        X = Y/normanew
        print('Iteración: k = ', k)
        print('Norma: ||A*X_k|| = ', normanew)
#        print('Lambdas: lambdas_k = \n', lambdas)
#        print('Vectores: X_k = \n', X)
        normaold = normanew
    if k == itermax and error >= tol:
        return False, 'ERROR potencia: no se alcanza convergencia.'
    else:
        print('\n Potencia: convergencia numérica alcanzada.')
        return True, normanew, lambdas, X

<span style="color:#FF0000"><b>Ejercicio 2.</b></span> Para la matriz dada en el ejercicio anterior, calcular mediante el método de la potencia inversa, si es posible, su autovalor de módulo menor y un autovector asociado. Utilizar la norma infinito y tomar como vector inicial el primer vector de la base canónica de $\mathbb{C}^4$.

In [4]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = \n", A)
X0 = array([[1], [0], [0], [0]])
print("X_0 = \n", X0)
exito, normaY, lambdas, X = potenciainv(A,X0,inf,200,1e-10)
if exito:
    print("Valor de las normas: ", normaY)
    print("Valores de los lambdas: ", lambdas)
    print("Autovector: ", X)
else:
    print("Error no convergencia")

A = 
 [[ -2   3  -3  11]
 [ -8   9 -12  20]
 [ -3   3  -6  15]
 [ -3   3  -3  12]]
X_0 = 
 [[1]
 [0]
 [0]
 [0]]
Iteración: k =  1
Norma: ||A*X_k|| =  1.0555555555555558
Iteración: k =  2
Norma: ||A*X_k|| =  0.9619883040935673
Iteración: k =  3
Norma: ||A*X_k|| =  0.9880108071597431
Iteración: k =  4
Norma: ||A*X_k|| =  0.9973698702975748
Iteración: k =  5
Norma: ||A*X_k|| =  0.9994927906457691
Iteración: k =  6
Norma: ||A*X_k|| =  0.9999078963436698
Iteración: k =  7
Norma: ||A*X_k|| =  0.9999838116923525
Iteración: k =  8
Norma: ||A*X_k|| =  0.9999972089830678
Iteración: k =  9
Norma: ||A*X_k|| =  0.9999995245045199
Iteración: k =  10
Norma: ||A*X_k|| =  0.999999919603527
Iteración: k =  11
Norma: ||A*X_k|| =  0.9999999864731213
Iteración: k =  12
Norma: ||A*X_k|| =  0.9999999977313572
Iteración: k =  13
Norma: ||A*X_k|| =  0.9999999996203193
Iteración: k =  14
Norma: ||A*X_k|| =  0.999999999936545
Iteración: k =  15
Norma: ||A*X_k|| =  0.9999999999894047

 Potencia: convergencia numé

Otra variante del método de la potencia es el método de la <b>potencia desplazada</b>, que consiste en aplicar el método de la potencia a la matriz $A-\mu\,I$, donde $\mu\in\mathbb{C}$ es una valor dado que nos permite mover la escala de los autovalores para localizar otros. Evidentemente se puede combinar el método de la potencia desplazada, con el método de la potencia inversa, dando lugar al método de la <b>potencia desplazada inversa</b>, que nos permite calcular el más próximo al valor de $\mu$.
<br>
Los programas <span style="font-family: Courier,monospace">potenciades()</span> y <span style="font-family: Courier,monospace">potenciadesinv()</span> implementarán dichos algoritmos; dichos programas deben tener un parámetro de entrada adicional, que es el valor de $\mu$.

In [12]:
def potenciades(A, X, des, norma, itermax, tol):
    m , n = shape(A)
    B = A - des*eye(n)
    exito, normanew, lambdas, X = potencia(B,X, norma, itermax,tol)
    return exito, normanew, lambdas, X

In [18]:
def potenciadesinv(A, X, des, norma, itermax, tol):
    m , n = shape(A)
    B = A - des*eye(n)
    exito, normanew, lambdas, X = potenciainv(B,X, norma, itermax,tol)
    return exito, normanew, lambdas, X

<span style="color:#FF0000"><b>Ejercicio 3.</b></span> Para la matriz dada en los ejercicios anteriores, calcular mediante el método de la potencia inversa y sus variantes toda la información posible sobre sus autovalores y autovectores.

In [5]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = \n", A)
X0 = array([[0], [0], [0], [1]])
print("X_0 = \n", X0)
exito, normaY, lambdas, X = potenciades(A,X0,9,inf,200,1e-10)
if exito:
    print("Valor de las normas: ", normaY)
    print("Valores de los lambdas: ", lambdas)
    print("Autovector: ", X)
else:
    print("Error no convergencia")

A = 
 [[ -2   3  -3  11]
 [ -8   9 -12  20]
 [ -3   3  -6  15]
 [ -3   3  -3  12]]
X_0 = 
 [[0]
 [0]
 [0]
 [1]]

 Potencia: convergencia numérica alcanzada.
Valor de las normas:  11.999999999836817
Valores de los lambdas:  [ -7.99999814+0.j -12.        +0.j -12.        +0.j   0.        +0.j]
Autovector:  [[-2.71972057e-11]
 [-1.00000000e+00]
 [-1.00000000e+00]
 [ 4.69792957e-19]]


In [6]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = \n", A)
X0 = array([[1], [1], [0], [0]])
print("X_0 = \n", X0)
exito, normaY, lambdas, X = potencia(A,X0,inf,200,1e-10)
if exito:
    print("Valor de las normas: ", normaY)
    print("Valores de los lambdas: ", lambdas)
    print("Autovector: ", X)
else:
    print("Error no convergencia")

A = 
 [[ -2   3  -3  11]
 [ -8   9 -12  20]
 [ -3   3  -6  15]
 [ -3   3  -3  12]]
X_0 = 
 [[1]
 [1]
 [0]
 [0]]

 Potencia: convergencia numérica alcanzada.
Valor de las normas:  1.0
Valores de los lambdas:  [1.+0.j 1.+0.j 0.+0.j 0.+0.j]
Autovector:  [[1.]
 [1.]
 [0.]
 [0.]]
