<div align="center"><span style="font-family: Arial,Helvetica,sans-serif; color:#0000FF""><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2021/22</span>
    <br>
    Facultad de Ciencias de la Universidad de Málaga
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. María López y Francisco José Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="color:#FF0000">Práctica número 5</span>
    </b></span></div>

In [1]:
from algoritmos import *


El objetivo de esta práctica es definir funciones <span style="font-family: Courier,monospace">Python</span> para resolver sistemas de ecuaciones lineales por <span style="color:#FF0000"><b>métodos de tipo Gauss</b></span>.
    <br>
Suponemos por tanto dadas $A\in\mathcal{M}_n(\mathbb{K})$ inversible y $B\in\mathbb{K}^n$, y desarrollamos métodos numéricos para calcular $X\in\mathbb{K}^n$ tal que $A\,X = B$.


El <span style="color:#FF0000"><b>método de Gauss</b></span> es un <b>método directo</b> de resolución del problema anterior que, formalmente, equivale a calcular una matriz $M\in\mathcal{M}_n(\mathbb{K})$ inversible tal que la matriz $M\,A$ sea <b>triangular superior</b> y, posteriormente, resolver el sistema $(M\,A)\,X = (M\,B)$ mediante un <b>método de remonte</b>.
<br>
En la práctica no se calcula dicha matriz $M$, sino que se va <b>triangularizando</b> la matriz $A$ mediante un <b>proceso iterativo</b> de $n-1$ etapas, en cada una de las cuales, tras colocar en la posición diagonal correspondiente un elemento no nulo (<b>pivote</b> de la iteración), se van haciendo nulos a través de adecuadas combinaciones lineales todos los elementos de la columna situados por debajo de la diagonal principal.


De manera similar, el <span style="color:#FF0000"><b>método de Gauss-Jordan</b></span> es un <b>método directo</b> de resolución del mismo problema que, formalmente, equivale a calcular una matriz $M\in\mathcal{M}_n(\mathbb{K})$ inversible tal que la matriz $M\,A$ sea <b>diagonal</b> y, posteriormente, resolver el sistema $(M\,A)\,X = (M\,B)$ que es inmediato debido al carácter diagonal de la matriz.
<br>
Tampoco aquí en la práctica se calcula dicha matriz $M$, sino que se va <b>diagonalizando</b> la matriz $A$ mediante un <b>proceso iterativo</b> de $n$ etapas, en cada una de las cuales, tras colocar en la posición diagonal correspondiente un elemento no nulo (<b>pivote</b> de la iteración), se van haciendo nulos a través de adecuadas combinaciones lineales todos los elementos de la columna excepto, evidentemente, el situado en la diagonal principal.

En ambos métodos tiene particular importancia la elección del elemento que en cada iteración ocupa la posición de pivote; las dos técnicas más habituales son la de <b>pivote parcial</b> y la de <b>primer pivote no nulo</b>.

Nos planteamos entonces como primer objetivo elaborar cuatro funciones, a las que daremos los nombres de <span style="font-family: Courier,monospace">gauss_pp()</span> y <span style="font-family: Courier,monospace">gauss_1p()</span>, para el <b>método de Gauss</b>, y <span style="font-family: Courier,monospace">gaussjordan_pp()</span> y <span style="font-family: Courier,monospace">gaussjordan_1p()</span>, para el de <b>Gauss-Jordan</b>, que implementan ambos algoritmos con las dos <b>técnicas de elección de pivote</b> indicadas anteriormente.
<br>
En todos los casos habrá dos <b>argumentos de entrada</b>, que son la matriz $A$ y el segundo miembro $B$, y como <b>salida</b> se obtienen también dos variables, siendo la primera de tipo booleano, en la que los valores <span style="font-family: Courier,monospace">True</span> o <span style="font-family: Courier,monospace">False</span> indica que se ha resuelto con éxito o no el sistema, y conteniendo la segunda variable la solución o un mensaje de error, respectivamente.


En todos los programas que realicemos se intentará utilizar la misma terminología y nombre de las variables que se ha visto en clases teóricas y de problemas; de esta manera es posible seguir mejor la programación del algoritmo correspondiente. En cualquier caso, resaltamos los siguientes hechos:
<ul>
<li> siempre se trabaja con la idea de que los programas puedan resolver múltiples sistemas lineales, todos con la misma matriz $A$, de manera simultánea, por lo que supondremos que $B$, y en consecuencia $X$ también, no es un vector de $\mathbb{K}^n$, sino un matriz de $\mathcal{M}_{n\times q}(\mathbb{K})$
<li> el bucle principal del proceso iterativo se realiza en la variable <span style="font-family: Courier,monospace">k</span>; recordamos que hay $n-1$ iteraciones en el método de Gauss y $n$ en el de Gauss-Jordan;</li>
<li> siempre que se haga referencia a las filas de las matrices se utiliza preferentemente el índice <span style="font-family: Courier,monospace">i</span>, mientras que para las columnas se utiliza el índice <span style="font-family: Courier,monospace">j</span>;</li>
<li>la fila en la que se localiza la posición del pivote de cada iteración (dependiendo de la estrategia utilizada), se identifica con el índice <span style="font-family: Courier,monospace">ik</span>;</li>
<li>son fácilmente identificables las instrucciones que permutan las filas de la matriz y del segundo miembro, en el caso de que el pivote de la iteración no se encuentre en la posición natural;</li>
<li>el proceso de hacer ceros por debajo de la diagonal (y por encima también en el caso de Gauss-Jordan), se realiza únicamente si el pivote elegido es mayor o igual en módulo que $10^{-200}$, que es el umbral de precisión elegido;</li>
<li>en cada iteración solamente se calculan los elementos de la matriz y del segundo miembro que cambian, no realizandose ningún cálculo supérfluo;</li>
<li>en las posiciones que deberían anularse en la iteración $k$-ésima, es decir, $a_{i,k}^{k+1}$, para $i=k+1,\ldots,n$, (en el caso de Gauss-Jordan también para $i=1,\ldots,k-1$) no se guardan ceros, sino que se almacenan los cocientes $\displaystyle\frac{\alpha_{i,k}^k}{\alpha_{k,k}^k}$, que son los elementos no nulos y no diagonales de la matrix de combinaciones lineales $E_k$ con signo cambiado;</li>
<li>en el método de Gauss, el proceso de resolución del sistema lineal se realiza mediante una llamada al programa <span style="font-family: Courier,monospace">remonte()</span>, que sería el que detectaría, si fuera el caso, la existencia de elementos nulos (o casi nulos) en la diagonal principal, es decir, detectaría si la matriz es o no regular;
<li>en el método de Gauss-Jordan, la resolución del(de los) sistema(s), es decir las $n$ divisiones de los elementos del(de los) segundo(s) miembro(s) por los elementos diagonales de $M\,A$, se realiza en el propio código, previa comprobación de que dichos elementos diagonales superen el umbral de precisión elegido.</li>
</ul>


<span style="color:#FF0000"><b>Ejercicio 1.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gaus_pp()</span> que implemente el algoritmo del <b>método de Gauss</b>, con estrategia de <b>pivote parcial</b>.

In [2]:
def gauss_pp(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gauss_pp: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)
    for k in range(n-1):
        pos = argmax(abs(gaussA[k:, k]))
        ik = pos+k
        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]
        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]
    exito, X = remonte(gaussA, gaussB)
    return exito, X

<span style="color:#FF0000"><b>Ejercicio 2.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gausjordan_pp()</span> que implemente el algoritmo del <b>método de Gauss-Jordan</b>, con estrategia de <b>pivote parcial</b>.

In [3]:
def gaussjordan_pp(A, B):
    (m, n) = shape(A)
    (p, q) = shape(B)
    if m != n or n != p or q < 1:
        return False, "gaussjordan_pp: error en las dimensiones"
    if A.dtype == complex or B.dtype == complex:
        gjA = array(A, dtype=complex)
        gjB = array(B, dtype=complex)
    else:
        gjA = array(A, dtype=float)
        gjB = array(B, dtype=float)
    for k in range(n):
        pos = argmax(abs(gjA[k:n, k]))
        ik = pos+k
        if ik != k:
            gjA[[ik, k], :] = gjA[[k, ik], :]
            gjB[[ik, k], :] = gjB[[k, ik], :]
        if abs(gjA[k, k]) >= 1e-15:
            for i in range(k):
                gjA[i, k] = gjA[i, k]/gjA[k, k]
                gjA[i, k+1:] = gjA[i, k+1:]-gjA[i, k]*gjA[k, k+1:]
                gjB[i, :] = gjB[i, :]-gjA[i, k]*gjB[k, :]
            for i in range(k+1, n):
                gjA[i, k] = gjA[i, k]/gjA[k, k]
                gjA[i, k+1:] = gjA[i, k+1:]-gjA[i, k]*gjA[k, k+1:]
                gjB[i, :] = gjB[i, :]-gjA[i, k]*gjB[k, :]
    if min(abs(diag(gjA))) < 1e-15:
        return False, "gaussjordan_pp: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n):
        X[i, :] = gjB[i, :]/gjA[i, i]
    return True, X


<span style="color:#FF0000"><b>Ejercicio 3.</b></span> Resolver los siguientes sistemas de ecuaciones lineales mediante los métodos de Gauss y de Gauss-Jordan, con estrategias de pivote parcial:
$$
(a) \quad \left( \begin{array}{rrrr}
1 & 2 & 1 & 4 \\ 2 & 0 & 4 & 3 \\ 4 & 2 & 2 & 1 \\ -3 & 1 & 3 & 2
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
13 \\ 28 \\ 20 \\ 6
\end{array} \right) \qquad (b) \quad \left( \begin{array}{rrrr}
20514 & 4424 & 978 & 224 \\ 4424 & 978 & 224 & 54 \\ 978 & 224 & 54 & 14 \\ 224 & 54 & 14 & 4
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) =  \left( \begin{array}{r}
20514 \\ 4424 \\ 978 \\ 224
\end{array} \right)
$$

In [5]:
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = ", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = ", B)
gauss_1p(A, B)

Matriz: A =  [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B =  [[13]
 [28]
 [20]
 [ 6]]


(True,
 array([[ 3.],
        [-1.],
        [ 4.],
        [ 2.]]))

array([[-6.93889390e-18,  8.33333333e-02,  8.33333333e-02,
        -1.66666667e-01],
       [ 6.66666667e-02, -3.44444444e-01,  3.22222222e-01,
         2.22222222e-01],
       [-2.00000000e-01,  1.16666667e-01,  1.16666667e-01,
         1.66666667e-01],
       [ 2.66666667e-01,  1.22222222e-01, -2.11111111e-01,
        -1.11111111e-01]])

<span style="color:#FF0000"><b>Ejercicio 4.</b></span> Calcular las inversas de las matrices de los sistemas anteriores.

In [7]:
inv(A)

array([[-6.93889390e-18,  8.33333333e-02,  8.33333333e-02,
        -1.66666667e-01],
       [ 6.66666667e-02, -3.44444444e-01,  3.22222222e-01,
         2.22222222e-01],
       [-2.00000000e-01,  1.16666667e-01,  1.16666667e-01,
         1.66666667e-01],
       [ 2.66666667e-01,  1.22222222e-01, -2.11111111e-01,
        -1.11111111e-01]])

In [ ]:
...

<span style="color:#FF0000"><b>Ejercicio 5.</b></span> Para el caso (a) del Ejercicio 3, escribir el sistema final triangular superior resultante $(M\,A)\,X = M\,B$ cuando se utiliza el método de Gauss. Identificar también las matrices $A_k$ y segundos miembros $B_k$, $k=1,2,\ldots,n$ del proceso iterativo.

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Ejercicio 6.</b></span> Para el caso (a) del Ejercicio 3, escribir el sistema final diagonal resultante $(M\,A)\,X = M\,B$ cuando se utiliza el método de Gauss-Jordan. Identificar también las matrices $A_k$ y segundos miembros $B_k$, $k=1,2,\ldots,n+1$ del proceso iterativo.
    </span></div>

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Ejercicio 7.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gaus_1p()</span> que implemente el algoritmo del <b>método de Gauss</b>, con estrategia de <b>primer pivote no nulo</b>.
    </span></div>

In [8]:
# esta en algoritmos.py

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Ejercicio 8.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gausjordan_1p()</span> que implemente el algoritmo del <b>método de Gauss-Jordan</b>, con estrategia de <b>primer pivote no nulo</b>.
    </span></div>

In [ ]:
# esta en algoritmos.py

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Ejercicio 9.</b></span> Resolver los sistemas de ecuaciones lineales del ejercicio 3 mediante los métodos de Gauss y de Gauss-Jordan, con estrategias de primer pivote no nulo.
    </span></div>

In [ ]:
...

In [ ]:
...