<div align="center"><span style="font-family: Arial,Helvetica,sans-serif; color:#0000FF""><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2021/22</span>
    <br>
    Facultad de Ciencias de la Universidad de Málaga
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. María López y Francisco José Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="color:#FF0000">Práctica número 8</span>
    </b></span></div>

In [1]:
from algoritmos import *

<span style="color:#FF0000"><b>Ejercicio 1.</b></span> Dado el vector $X$ que aparece en la celda siguiente, calcular la matriz de Householder $H(X)$.

In [2]:
X = array([[1], [2], [3], [4]])
den = conjugada(X)@X
N = X@conjugada(X)
fr = 2/den
n = size(X)
H = eye(n,n) - fr * N
print(H)

[[ 0.93333333 -0.13333333 -0.2        -0.26666667]
 [-0.13333333  0.73333333 -0.4        -0.53333333]
 [-0.2        -0.4         0.4        -0.8       ]
 [-0.26666667 -0.53333333 -0.8        -0.06666667]]


<span style="color:#FF0000"><b>Ejercicio 2.</b></span> Dado el vector $X$ que aparece en la celda siguiente, calcular las matrices de Householder $H(Z_i)$, $i=1,2$, tales que el vector $H(Z_i)\,X$ tiene nulas todas sus componentes excepto, quizás, la primera.

In [3]:
X = array([[1], [0], [0], [0]])
print(Householder(X))

[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


<span style="color:#FF0000"><b>Ejercicio 3.</b></span> Considera el sistema lineal $A\,X = B$, así como el sistema perturbado $A\,\bar{X} = \bar{B}$, donde
$$
A = \left( \begin{array}{rrrr}
10 & 1 & 4 & 0 \\ 1 & 10 & 5 & -1 \\ 4 & 5 & 10 & 7 \\ 0 & -1 & 7 & 9
\end{array} \right)\,, \quad B = \left( \begin{array}{r}
15 \\ 15 \\ 26 \\ 15
\end{array} \right) \quad y \quad \bar{B} = \left( \begin{array}{r}
16 \\ 16 \\ 25 \\ 16
\end{array} \right)\,.
$$
Calcular $X$ y $\bar{X}$ (mediante el método de Gauss con estrategia de pívot parcial) y verificar la desigualdad
$$
\frac{\|\delta X\|_2}{\|X\|_2} \le \rm{cond}_2(A)\,\frac{\|\delta B\|_2}{\|B\|_2}\,.
$$

In [5]:
A = array([[10,1,4,0],[1,10,5,-1],[4,5,10,7],[0,-1,7,9]])
B = array([[15],[15],[26],[15]])
B1 = array([[16],[16],[25],[16]])
print(gauss_pp(A,B))
print(gauss_pp(A,B1))


exito, X = gauss_pp(A, B)
exitop, Xp = gauss_pp(A, B1)
Xdelta = X - Xp
Bdelta = B - B1
m = norma_vec(Xdelta, 2) / norma_vec(X, 2)
M = norma_mat(A, 2)*norma_mat(inv(A), 2)*norma_vec(Bdelta, 2) / norma_vec(B, 2)
print("Comprobación: ", m, "<=", M)

(True, array([[1.],
       [1.],
       [1.],
       [1.]]))
(True, array([[  832.],
       [ 1324.],
       [-2407.],
       [ 2021.]]))
Comprobación:  1754.975355950986 <= 1947.5701637220152


<span style="color:#FF0000"><b>Ejercicio 4.</b></span> Calcular $\rm{cond}_p(A_2)$, $p=1,2,\infty$, donde $A_2$ es la matriz triangular superior resultante de aplicar el método de Gauss al sistema
$$
\left\{ \begin{array}{rcrcr}
10^{-4}\,x_1 & + & x_2 & = & 1\,, \\ x_1 & + & x_2 & = & 2\,.
\end{array} \right.
$$
Comparar los resultados cuando no se utiliza ninguna estrategia de pivot y cuando se utiliza una estrategia de pivot parcial.

In [1]:
from algoritmos import *
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

A = array([[10**(-4),1],[1,1]])
B = array([[1],[2]])
A2 = matrizTriangularGauss(A,B)
print(A2)
print(cond(A2,1))
print(cond(A2,2))
print(cond(A2,inf))

[[1.     1.    ]
 [0.     0.9999]]
4.000200020002
2.6181510933132386
4.000200020002


<span style="color:#FF0000"><b>Ejercicio 5.</b></span> Se consideran las matrices $A = \left( \begin{array}{ccc} 1 & 2 & -2 \\ 1 & 1 & 1 \\ 2 & 2 & 1 \end{array} \right)$ y $B = \left( \begin{array}{ccc} 2 & -1 & 1 \\ 2 & 2 & 2 \\ -1 & -1 & 2 \end{array} \right)$. Demostrar que para la primera matriz se tiene que $\rho(J)<1<\rho({\cal L}_1)$ mientras que para la segunda se tiene que $\rho({\cal L}_1)<1<\rho(J)$.

In [2]:
A = array([[1,2,-2],[1,1,1],[2,2,1]])
E = -1*tril(A,k=-1)
print(E)
F = -1*triu(A,k=1)
print(F)
D = A + E + F
print(D)
exito, Di = gauss_pp(D,eye(3))
J = Di@(E+F)
pJ = max(abs(eigvals(J)))
print(pJ)

exito2, dmenoseinv = gauss_pp(D-E,eye(3))
L1 = dmenoseinv@F
pL1 = max(abs(eigvals(L1)))
print(pL1)

print(pJ < 1 < pL1)

[[ 0  0  0]
 [-1  0  0]
 [-2 -2  0]]
[[ 0 -2  2]
 [ 0  0 -1]
 [ 0  0  0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
1.0812771377650137e-05
2.0
True
