# Práctica 3. Normas matriciales 

El objetivo de esta práctica es trabajar con normas matriciales, subordinadas o no a normas vectoriales. No obstante previamente trabajamos con algunos comandos que calculan autovalores y autovectores de matrices.

Dada una matriz $A\in \mathcal{M}_n(\mathbb{K})$, el comando **`eig()`**, cuyo único parámetro de entrada es la matriz $A$, tiene dos parámetros de salida, siendo el primero un vector (`array` de dimensión 1 al que llamamos, por ejemplo, $d$) que contiene los autovalores de la matriz, y el segundo una matriz (`array` de dos dimensiones a la que llamamos, por ejemplo, $U$) que contiene, en cada columna, los autovectores asociados.

Hay que tener cuidado porque la matriz $U$ no siempre es inversible, lo que ocurre en el caso de que $A$ no es diagonalizable; se puede comprobar esta situación calculando el determinante de la matriz $U$ con el comando **`det()`**, cuyo único parámetro de entrada es la matriz de la que se quiere calcular el determinante.

Por otro lado, la matriz $U$, cuyas columnas (que aparecen como vectores normalizados) son los autovectores asociados a los autovalores del vector $d$ (en el mismo orden), verifica las propiedades habituales: autovectores asociados a autovalores diferentes son linealmente independientes, y si la matriz es normal los autovectores son ortogonales (ortonormales pues están normalizados). No obstante, si aparece un autovalor múltiple los autovectores asociades al mismo autovalor no tienen por qué ser linealmente independientes (si la matriz no es diagonalizable), ni por supuesto ortogonales (aún en el caso de que la matriz sea normal).

En el caso de que haya efectivamente diagonalización se puede comprobar que $U^{−1}AU = D$, siendo $D = \mathrm{diag}(d)$. 

---

In [28]:
# Cargamos los módulos necesarios
from numpy import *
from algoritmos import *
from numpy.linalg import *
#from numpy import abs, sum, max, min

**Ejercicio 1:** Calcular los autovalores y autovectores e indicar si son o no diagonalizables las siguientes matrices. En caso de que sean diagonalizables, determinar si la matriz de paso es unitaria.
$$
\mathrm{a}.A=\begin{pmatrix}
3 & 1\\
0 & 1
\end{pmatrix}
; \quad 
\mathrm{b}.A=\begin{pmatrix}
2 & 0 & 2\\
0 & 1 & 0\\
2 & 0 & -1
\end{pmatrix}
; \quad
\mathrm{c}.A=\begin{pmatrix}
1 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & -2\\
1 & 0 & -2 & 5
\end{pmatrix}
$$
$$
\mathrm{d}.A=\begin{pmatrix}
7 & 1 & 1 & 1\\
1 & 7 & 1 & 1\\
1 & 1 & 7 & 1\\
1 & 1 & 1 & 7
\end{pmatrix}
; \quad
\mathrm{e}.A=\begin{pmatrix}
1 & 0 & 0\\
-3 & 1 & 0\\
4 & 7 & 1
\end{pmatrix}
; \quad 
\mathrm{f}.A=\begin{pmatrix}
0 & -2\\
2 & 0
\end{pmatrix}
$$

In [29]:
# Ejercicio 1.a
print("Ejercicio 1.a.")
A = array([[3, 1], [0, 1]])
print("A = ")
print(A)

# Calculamos autovalores y autovectores
d, U = eig(A)

# Imprimimos por pantalla los autovalores (d) y autovectores (U)
print("Autovalores de A")
print(d)
print("Autovectores de A")
print(U)

# ¿Es la matriz diagonalizable
detU = det(U)
print("det(U) =" ,detU)
if abs(detU) < 1e-15:
    print("Matriz NO diagonalizable")
else:
    print("Matriz SI diagonalizable")
    print("||U^(-1) - U*||_e = " ,norm(inv(U) - conjugada(U)))

# Repetir el proceso para el resto de matrices

Ejercicio 1.a.
A = 
[[3 1]
 [0 1]]
Autovalores de A
[3. 1.]
Autovectores de A
[[ 1.         -0.4472136 ]
 [ 0.          0.89442719]]
det(U) = 0.8944271909999159
Matriz SI diagonalizable
||U^(-1) - U*||_e =  0.7071067811865476


---
Dada una matriz $A\in \mathcal{M}_n(\mathbb{K})$, el comando **`svd()`** , cuyo parámetro de entrada es la matriz $A$, tiene tres parámetros de salida, siendo el segundo un vector (`array` de dimensión 1 al que llamamos, por ejemplo, $s$) que contiene los valores singulares de la matriz, y el primero y tercero dos matrices ortogonales-unitarias (`array` de dos dimensiones a las que llamamos, por ejemplo, $U$ y $V$ ) de la descomposición de $A$ en valores singulares; estas dos matrices son tales que $U S V = A$, siendo $S = \mathrm{diag}(s)$.


**Ejercicio 2:** Dada la matriz
$$A=\begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}$$

comprobar que los valores singulares de $A$ son efectivamente las raíces cuadradas positivas de los autovalores de $A^∗ A$.


In [30]:
print("\n Ejercicio 2.")
A = array([[1, 2 , 3], [4, 5 , 6], [7, 8 , 9]])
print("Matriz: A = ")
print(A)
# Calculamos las raíces cuadradas de los autovalores de A^* A
d,P = eig(conjugada(A)@A)   #@ es la multiplicacion matricial
raizd = sqrt(d)

# Calculamos los valores singulares de la matriz A:
U,s,V = svd(A)

# Comparamos ambos resultados
print("Raices de los autovalores")
print(raizd)
print("Valores singulares de A")
print(s)


 Ejercicio 2.
Matriz: A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Raices de los autovalores
[1.68481034e+01 1.06836951e+00 8.53406751e-08]
Valores singulares de A
[1.68481034e+01 1.06836951e+00 4.41842475e-16]


**Ejercicio 3:** Calcular la descomposición en valores singulares
de las matrices del ejercicio 1.

$$
\mathrm{a}.A=\begin{pmatrix}
3 & 1\\
0 & 1
\end{pmatrix}
; \quad 
\mathrm{b}.A=\begin{pmatrix}
2 & 0 & 2\\
0 & 1 & 0\\
2 & 0 & -1
\end{pmatrix}
; \quad
\mathrm{c}.A=\begin{pmatrix}
1 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & -2\\
1 & 0 & -2 & 5
\end{pmatrix}
$$
$$
\mathrm{d}.A=\begin{pmatrix}
7 & 1 & 1 & 1\\
1 & 7 & 1 & 1\\
1 & 1 & 7 & 1\\
1 & 1 & 1 & 7
\end{pmatrix}
; \quad
\mathrm{e}.A=\begin{pmatrix}
1 & 0 & 0\\
-3 & 1 & 0\\
4 & 7 & 1
\end{pmatrix}
; \quad 
\mathrm{f}.A=\begin{pmatrix}
0 & -2\\
2 & 0
\end{pmatrix}
$$

In [31]:
# Ejercicio 3.a.
print("\n Ejercicio 3.a.")
A = array([[3, 1], [0, 1]])
# Descomposición en valores singulares.
U,s,V = svd(A)
# Comprobamos que USV=A
print("||U S V - A||_e = " ,norm(U@diag(s)@V - A))
print(U@diag(s)@V - A)
# ¿Son las matrices ortogonales U y V unitarias?
# ...

# Ejercicio 3.b.
print("\n Ejercicio 3.b.")
B = array([[2, 0,2], [0, 1, 0], [2, 0, -1]])
# Descomposición en valores singulares.
U,s,V = svd(B)
# Comprobamos que USV=A
print("||U S V - B||_e = " ,norm(U@diag(s)@V - B))
# ¿Son las matrices ortogonales U y V unitarias?
# ...


 Ejercicio 3.a.
||U S V - A||_e =  1.0175362097255202e-15
[[ 8.88178420e-16  4.44089210e-16]
 [ 0.00000000e+00 -2.22044605e-16]]

 Ejercicio 3.b.
||U S V - B||_e =  2.560743305106871e-15


---
Pasamos ahora a trabajar con normas matriciales.

Se recuerda que es posible definir una norma matricial en $\mathcal{M}_n(\mathbb{K})$ a partir de una norma vectorial en $\mathbb{K}^n$ poniendo
$$
\|A\| = \max_{X\in\mathbb{K}^n-\{0\}} \frac{\|A\,X\|}{\|X\|} = \max_{\|X\|=1} \|A\,X\| = \max_{\|X\|\le1} \|A\,X\|\,;
$$
esta norma matricial recibe el nombre de norma subordinada a la norma vectorial considerada, y en el caso de la normas vectoriales más habituales se tienen las caracterizaciones
\begin{eqnarray*}
\|A\|_\infty & = & \max_{i=1,\ldots,n} \sum_{j=1}^n |a_{i,j}|\,, \\
\|A\|_1 & = & \max_{j=1,\ldots,n} \sum_{i=1}^n |a_{i,j}|\,, \\
\|A\|_2 & = & \sqrt{\varrho(A^*\,A)} = \sqrt{\varrho(A\,A^*)}\,.
\end{eqnarray*} 
Por otro lado, la función $\|\cdot\|_E\colon\mathcal{M}_n(\mathbb{K})\to\mathbb{R}^+/A\mapsto\|A\|_E$, dada por
$$
\|A\|_E = \left( \sum_{i=1}^n \sum_{j=1}^n |a_{i,j}|^2 \right)^{1/2}
$$
define también una norma matricial, no subordinada, llamada norma euclídea, de Shur, o de Frobenius.

**Ejercicio 4:** Definir una función, de nombre **`norma_mat()`** con dos argumentos de entrada, el primero una matriz cuadrada, y el segundo el índice $p$ (que puede adoptar los valores `inf`,1,2, o la cadena `'fro'`), que devuelva la norma matricial correspondiente. 

Aplicar la función **`norma_mat()`** para calcular las normas $\infty, 1, 2$ y de Frobenius de las matrices 
$$
A = \begin{pmatrix}
1 & 2\\
3 & 4
\end{pmatrix}
 \qquad  \mbox{ y } \qquad
B = \begin{pmatrix}
1 & -2 & 3\\
-4i & 5 & -6\\
7 & 8i & 9
\end{pmatrix}
$$

Comprobar los resultados obtenidos con los de la funcion **`norm()`** de Python; esta función tiene los mismos parámetros de entrada que la creada por nosotros, y cuando el primero de ellos es una matriz (`array`de dos dimensiones), calcula normas matriciales. 



In [32]:
# función norma_mat() versión 1
def norma_mat(A, p):
    A = array(A, dtype ="complex")
    if p == inf:
        return max(sum(abs(A), axis = 1))
    elif p == 1:
        return max(sum(abs(A), axis = 0))
    elif p == 2:
        return sqrt(max(abs(eig(conjugada(A)@A)[0])))
    elif p == 'fro':
        return sqrt(sum(abs(A)**2))
    else:
        return "Error norma_mat: valor de p."


# Ejercicio 4.
print("\n Ejercicio 4.")
A = array([[1, 2], [3, 4]])
B = array([[1, -2., 3e0], [-4j, 5, -6.], [7e0, 8j, 9]])
print("Normas matriciales.")
print("A = ", A, "\nB = ", B)
print("Norma inf (propio): ", norma_mat(A, inf), norma_mat(B, inf))
print("Norma inf (Python): ", norm(A, inf), norm(B, inf))
print("Norma 1 (propio): ", norma_mat(A, 1), norma_mat(B, 1))
print("Norma 1 (Python): ", norm(A, 1), norm(B, 1))
print("Norma 2 (propio): ", norma_mat(A, 2), norma_mat(B, 2))
print("Norma 2 (Python): ", norm(A, 2), norm(B, 2))
print("Norma euclídea (propio): ", norma_mat(A, 'fro'), norma_mat(B, 'fro'))
print("Norma euclídea (Python): ", norm(A, 'fro'), norm(B, 'fro'))
print("Norma 3 (propio): ", norma_mat(A, 3), norma_mat(B, 3))
print("Norma 3 (Python): ", norm(A, 3), norm(B, 3))


 Ejercicio 4.
Normas matriciales.
A =  [[1 2]
 [3 4]] 
B =  [[ 1.+0.j -2.+0.j  3.+0.j]
 [-0.-4.j  5.+0.j -6.+0.j]
 [ 7.+0.j  0.+8.j  9.+0.j]]
Norma inf (propio):  7.0 24.0
Norma inf (Python):  7.0 24.0
Norma 1 (propio):  6.0 18.0
Norma 1 (Python):  6.0 18.0
Norma 2 (propio):  5.464985704219043 15.786285706001541
Norma 2 (Python):  5.464985704219043 15.786285706001534
Norma euclídea (propio):  5.477225575051661 16.881943016134134
Norma euclídea (Python):  5.477225575051661 16.881943016134134
Norma 3 (propio):  Error norma_mat: valor de p. Error norma_mat: valor de p.


ValueError: Invalid norm order for matrices.

**Ejercicio 5** Intentar dar una aproximación de la norma matricial de $A$, para $p=1,2,\mathrm{inf}$, calculando el máximo de los cocientes que la define, $$\|A\| = \max_{X\in\mathbb{K}^n-\{0\}} \frac{\|A\,X\|}{\|X\|}$$ no sobre el conjunto de todos los vectores no nulos (cosa imposible), sino sobre un conjunto finito de vectores aleatorios suficientemente grande. Comparar estos resultados con los dados por la función `norm` implementada en Python. Repetir el ejercicio restringiendo el cálculo del máximo a los vectores de norma 1. 

In [ ]:
A=array([[1,2],[3,4]])
B=array([[1,-2,3],[-4j,5,-6],[7,8j,9]])
aprox_norma_mat(A,1,1000)

Norma matricial:  6.0
Aproximación:  5.999597741878667
