<span style="font-family: Arial,Helvetica,sans-serif; font-size: medium">
<div align="center"><span style="font-size: x-large; color:#0000FF"><b>Métodos Numéricos II</b></span></div>
<div align="center"><span style="font-size: large; color:#0000FF"><b>Segundo de Grado en Matemáticas - Curso 2021/22</b></span></div>
<div align="center"><span style="font-size: medium; color:#0000FF"><b>Facultad de Ciencias de la Universidad de Málaga</b></span></div>
<div align="center"><span style="font-size: small; color:#0000FF"><b>Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</b></span></div>
<div align="center"><span style="font-size: small; color:#0000FF"><b>Profs. María López Fernández y Francisco José Palma Molina (Área Conocimiento de Matemática Aplicada)</b></span></div>
<div align="center"><span style="font-size: medium; color:#FF0000"><b>Práctica número 2</b></span></div></span>

In [1]:

# -*- coding: utf-8 -*-
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

<span style="font-family: Arial,Helvetica,sans-serif; font-size: medium">
    <b>Ejercicio 1:</b> crear una matriz de tamaño 20, que sea tridiagonal con elementos diagonales iguales a 2 y elementos sub-diagonales y supra-diagonales iguales a -1.
</span>

In [2]:
# Ejercicio 1.
print("Ejercicio 1.")
A = 2*eye(20) + eye(20, k=1) - eye(20, k=-1)
# print("A = ", A)
def wilkinson(n):
    diag = array([])
    for i in range(n):
        diag.insert(n -i)
    return diag

print(diag)

Ejercicio 1.
<function diag at 0x7f771c117d00>


<b>Ejercicio 2:</b> dada la matriz $A = \left( \begin{array}{cc} 1 & 2 \\ 3 & 4 \end{array} \right)$, construir las matrices $B = \left( \begin{array}{c|c} A & 2\,A \\ \hline 3\,A & 4\,A \end{array} \right)$ y $C = \left( \begin{array}{c|c|c} A & I & \\ \hline I & A & I \\ \hline & I & A \end{array} \right)$. Con la ayuda del comando <span style="font-family: Courier,monospace">det()</span>, cuyo único argumento es una matriz, calcular los determinantes de las matrices anteriores.

In [5]:
# Ejercicio 2.
print("Ejercicio 2.")
A = array([[1, 2], [3, 4]])
print("A = ", A, "\ndet(A) = ", det(A))
B = vstack([hstack([A, 2*A]), hstack([3*A, 4*A])])
print("B = ", B, "\ndet(B) = ", det(B))
C = vstack([hstack([A, eye(2), zeros((2,2))]),hstack([eye(2), A, eye(2)]), hstack([zeros((2,2)), eye(2), A ])])
print("C = ", C, "\ndet(C) = ", det(C))

Ejercicio 2.
A =  [[1 2]
 [3 4]] 
det(A) =  -2.0000000000000004
B =  [[ 1  2  2  4]
 [ 3  4  6  8]
 [ 3  6  4  8]
 [ 9 12 12 16]] 
det(B) =  15.999999999999998
C =  [[1. 2. 1. 0. 0. 0.]
 [3. 4. 0. 1. 0. 0.]
 [1. 0. 1. 2. 1. 0.]
 [0. 1. 3. 4. 0. 1.]
 [0. 0. 1. 0. 1. 2.]
 [0. 0. 0. 1. 3. 4.]] 
det(C) =  99.99999999999996



<b>Ejercicio 3:</b> construir una matriz $A=(a_{ij})\in\mathcal{M}_{10}(\mathbb{R})$ tal que $a_{ij}=10\,(i-1)+j$, para todo $i,j=1,2,\ldots,10$. Construir también las matrices $B,C\in\mathcal{M}_{10}(\mathbb{R})$ que coinciden con $A$, excepto que en $B$ permutan entre sí las filas y columnas segunda y quinta, y en $C$ a la quinta fila de $A$ se le suma 3 veces la segunda fila.

In [10]:
# Ejercicio 3.
print("Ejercicio 3.")
A = reshape(arange(0,100,1), (10,10))
print("A = ", A)
B = array(A)
print("Permutación de las filas 2 y 4")
B[[1, 4], :] = B[[4, 1], :]
print("B = ", B)
C = array(A)
print("A toda la fila 4, le suma 3 veces el contenido de la fila 1") ##no entiendo bien que pasa
C[4, :] += 3*C[1, :]
print("C = ", C)

Ejercicio 3.
A =  [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Permutación de las filas 2 y 4
A toda la fila 4, le suma 3 veces el contenido de la fila 1
C =  [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 70  74  78  82  86  90  94  98 102 106]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]]


<b>Ejercicio 4:</b> se llama <b>matriz de Hilbert de orden $n$</b> a la matriz $H=(h_{ij})\in\mathcal{M}(\mathbb{R})$ tal que $h_{ij}=\frac{1}{i+j-1}$, para todo $i,j=1,2,\ldots,n$. Construir e imprimir una matriz de Hilbert de orden 5, así como todas sus submatrices principales (que son también matrices de Hilbert); calcular también el determinante de estas submatrices.

In [4]:
# Ejercicio 4.
print("Ejercicio 4.")
n = 5
H = zeros((n,n))
for i in range(n):
    for j in range(n):
        H[i, j] = 1/(i+j+1)
print("H = ", H)
for k in range(n):
    print("Submatriz principal de orden: ", k+1)
    print("H^(", k+1, ") = ", H[:k+1, :k+1])
    print("det H^(", k+1, ") = ",  det(H[:k+1, :k+1]))

Ejercicio 4.
H =  [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
Submatriz principal de orden:  1
H^( 1 ) =  [[1.]]
det H^( 1 ) =  1.0
Submatriz principal de orden:  2
H^( 2 ) =  [[1.         0.5       ]
 [0.5        0.33333333]]
det H^( 2 ) =  0.08333333333333333
Submatriz principal de orden:  3
H^( 3 ) =  [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
det H^( 3 ) =  0.00046296296296296146
Submatriz principal de orden:  4
H^( 4 ) =  [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
det H^( 4 ) =  1.6534391534392996e-07
Submatriz principal de orden:


<b>Ejercicio 5:</b> se llama <b>matriz de Vandermonde de orden $n$</b> a la matriz $V=(v_{ij})\in\mathcal{M}(\mathbb{K})$ tal que $v_{ij}={\alpha_i}^{j-1}$, para todo $i,j=1,2,\ldots,n$, siendo $\alpha_i\in\mathbb{K}$, para $i=1,2,\ldots,n$; en el caso en que $\alpha_i=i$, construir e imprimir una matriz de Vandermonde de orden 5.
<br>
Para suprimir líneas (filas o columnas) de una matriz, se puede utilizar el comando <span style="font-family: Courier,monospace">delete()</span>, cuyos tres argumentos son una matriz, la(s) línea(s) que se quieren suprimir, y <span style="font-family: Courier,monospace">axis=</span> para indicar si se suprimen filas o columnas. Por otro lado, el comando <span style="font-family: Courier,monospace">inv()</span>, cuyo único argumento es una matriz, calcula la inversa de la matriz dada (supuesta regular).
<br>
Construir la matriz de cofactores de la matriz de Vandermonde anterior y comprobar que la transpuesta de la misma, dividida por su determinante, es la inversa.


In [ ]:
# Ejercicio 5.
print("Ejercicio 5.")
n = 5
V = zeros((n,n))
for i in range(n):
    for j in range(n):
        V[i, j] = i**j
print("V = ", V)
cofV = zeros((n,n))
for i in range(n):
    for j in range(n):
        cofV[i, j] = ???
print("cof(V) = ", cofV)
print("V^(-1) = ", inv(V))
print("det(V)^(-1)*cof(V)^t = ", transpose(cofV)/det(V))
print("Comprobación: ", max(abs(inv(V)-transpose(cofV)/det(V))))

<b>Ejercicio 6:</b> para calcular los autovalores y autovectores de una matriz se dispone del comando <span style="font-family: Courier,monospace">eig()</span>, cuyo único argumento de entrada es una matriz. Este comando devuelve un vector conteniendo los autovalores (en orden arbitrario) y una matriz cuyas columnas son los autovectores correspondientes. En el caso de que la matriz sea diagonalizable esta matriz de autovectores es invertible y se trata de una matriz de paso (no necesariamente ortogonal-unitaria) a la forma diagonal.
    <br>
    Calcular los autovalores y autovectores, y diagonalizar cuando sea posible, las matrices:
$$
A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right) \, A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right) \, A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right) \, A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right) \, A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right) \, A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)
$$

In [7]:
# Ejercicio 6-a.
A = array([[3, 1], [0,1]])
print("Los autovalores de la primera matriz son: ", eig(A))

Los autovalores de la primera matriz son:  (array([3., 1.]), array([[ 1.        , -0.4472136 ],
       [ 0.        ,  0.89442719]]))


In [10]:
# Ejercicio 6-b.
B = array([[0, -2], [2,0]])
print("Los autovalores de la segunda matriz son: ", eig(B))

Los autovalores de la segunda matriz son:  (array([0.+2.j, 0.-2.j]), array([[0.        +0.70710678j, 0.        -0.70710678j],
       [0.70710678+0.j        , 0.70710678-0.j        ]]))


In [9]:
# Ejercicio 6-c.
C = array([[2, 0,2], [0,1,0], [2, 0, -1]])
print("Los autovalores de la tercera matriz son: ", eig(C))

Los autovalores de la tercera matriz son:  (array([ 3., -2.,  1.]), array([[ 0.89442719, -0.4472136 ,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.4472136 ,  0.89442719,  0.        ]]))


In [ ]:
# Ejercicio 6-d.


In [ ]:
# Ejercicio 6-e.


In [ ]:
# Ejercicio 6-f.


<span style="font-family: Arial,Helvetica,sans-serif; font-size: medium">
    Durante el desarrollo de las clases prácticas vamos a crear un fichero <span style="font-family: Courier,monospace">Python</span>, al que daremos el nombre de <span style="font-family: Courier,monospace">algoritmos.py</span> donde almacenaremos todas aquellas funciones propias que definamos durante el curso. A partir de ese momento, podremos utilizar dichas funciones en cualquier hoja de trabajo que estemos utilizando, sin más que importar al principio de la misma las funciones que hayamos definido mediante la siguiente instrucción. (Cada vez que se modifique dicho fichero, no olvidar guardar su contenido y reinicializar el núcleo de la hoja de trabajo.)
</span>

In [5]:
from algoritmos import *

<b>Ejercicio 7:</b> definir una función, de nombre <span style="font-family: Courier,monospace">conjugada()</span>, con un único argumento de entrada que sea una matriz y que devuelva la conjugada de la misma. Comprobar la validez de la función construida calculando las conjugadas de las matrices
$$
A = \left( \begin{array}{cc} 1 & 4\,i \\ 2 & -5\,i \\ 3 & 6+6\,i \end{array} \right) \quad B = \left( \begin{array}{cc} 1 & 4\,i \end{array} \right) \quad C = \left( \begin{array}{c} 1 \\ 2 \\ 3 \end{array} \right)
$$

In [11]:
# Ejercicio 7-a.
A = array([[1, 4j], [2, -5j], [3, 6 +6j]])
print("La conjugada de A", A,  "es ", conjugada(A))

La conjugada de A [[ 1.+0.j  0.+4.j]
 [ 2.+0.j -0.-5.j]
 [ 3.+0.j  6.+6.j]] es  [[ 1.-0.j  2.-0.j  3.-0.j]
 [ 0.-4.j -0.+5.j  6.-6.j]]


In [12]:
# Ejercicio 7-b.
B = array([1, 4j])
print("La conjugada de B", B,  "es ", conjugada(B))

La conjugada de A [1.+0.j 0.+4.j] es  [1.-0.j 0.-4.j]


In [13]:
# Ejercicio 7-c.
C = array([1, 2, 3])
print("La conjugada de C", C,  "es ", conjugada(C))

La conjugada de C [1 2 3] es  [1 2 3]


<b>Ejercicio 8:</b> definir una función, de nombre <span style="font-family: Courier,monospace">traza()</span>, con un único argumento de entrada que sea una matriz cuadrada y que devuelva la traza de la misma. Comprobar la validez de la función construida calculando las trazas de las matrices
$$
A = \left( \begin{array}{cc} 1 & 4\,i \\ 2 & -5\,i \end{array} \right) \quad B = \left( \begin{array}{cc} 1 & 4\,i \\ 2 & -5\,i \\ 3 & 6+6\,i \end{array} \right)
$$

In [14]:
# Ejercicio 8-a.
A = array([[1, 4j], [2, -5j]])
print("La traza de A es", traza(A))

La traza de A es (1-5j)


In [15]:
# Ejercicio 8-b.
B = array([[1, 4j], [2, -5j], [3, 6 + 6j]])
print("La traza de B es", traza(B))

La traza de B es (1-5j)


Se recuerda que en $\mathbb{K}^n$, para cada $p\ge1$, las funciones $\|\cdot\|_p\colon\mathbb{K}^n\to\mathbb{R}^+/X\mapsto\|X\|_p$, dadas por
$$
\|X\|_p = \left( \sum_{i=1}^n |x_i|^p \right)^{1/p}\,,
$$
así como la función $\|\cdot\|_\infty\colon\mathbb{K}^n\to\mathbb{R}^+/X\mapsto\|X\|_\infty$, dada por
$$
\|X\|_\infty = \max_{i=1,2,\ldots,n} |x_i|\,,
$$
definen normas vectoriales. Además se demuestra que para todo $X\in\mathbb{K}^n$ la sucesión $\{\|X\|_p\}_{p\in\mathbb{N}}$ es convergente y su límite es justamente $\|X\|_\infty$.

<b>Ejercicio 9:</b> definir una función, de nombre <span style="font-family: Courier,monospace">norma_vec()</span>, con dos argumentos de entrada, el primero un vector o una matriz fila o columna, y el segundo el índice $p$ (número real mayor o igual a 1, o bien la cadena de caracteres <span style="font-family: Courier,monospace">inf</span>), que devuelva la norma vectorial correspondiente. Comparar los resultados obtenidos con los que devuelve el comando <span style="font-family: Courier,monospace">norm()</span>; este comando de <span style="font-family: Courier,monospace">Python</span> tiene los mismos argumentos de entrada que la función creada anteriormente, pero el primer argumento debe ser un vector (<span style="font-family: Courier,monospace">array</span> de 1 dimensión) para que calcule normas vectoriales, a diferencia de la función creada que calcula normas vectoriales tanto de vectores, como de matrices filas o columnas. Comprobar la validez de la función construida calculado diferentes normas vectoriales tanto de un vector, como de una matriz fila o columna; la comparación con la función de <span style="font-family: Courier,monospace">Python</span> solamente se puede hacer con el vector.

Para comprobar la validez de la función construida se proponen varios ejemplos, utilizando para ello un vector de elementos enteros, así como una matriz fila y una matriz columna de elementos reales o complejos; se van a poner de mafiesto algunos resultados <i>no deseados</i>. En los ejemplos propuestos se aprovecha también para comparar los resultados con la función de <span style="font-family: Courier,monospace">norm()</span> de <span style="font-family: Courier,monospace">Python</span>; esta función sirve indistintamente para calcular normas vectoriales o matriciales, en función de que se utilice como argumento un vector o una matriz. Es por ello que solamente lo utilizamos con el vector $x$ (y no con las matrices $X$ e $Y$).

In [16]:
# Ejercicio 9. Ejemplos de arrays para probar.
print("Ejercicio 9.")
x = array([7, -8, 9])
X = array([[7., -8., 9e0]])
Y = array([[7j], [-8j], [9j]])
print("x = ", x, "\nX = ", X, "\nY =\n ", Y)


Ejercicio 9.
x =  [ 7 -8  9] 
X =  [[ 7. -8.  9.]] 
Y =
  [[ 0.+7.j]
 [-0.-8.j]
 [ 0.+9.j]]


In [18]:
print("Norma inf (propio): ", norma_vec(X, inf))
      
print("Norma inf (Python): ", norm(X, inf))
      

Norma inf (propio):  9.0
Norma inf (Python):  24.0


In [19]:
print("Norma 1 (propio): ", norma_vec(X, 1))
      
print("Norma 1 (Python): ", norm(X, 1))
      

Norma 1 (propio):  24.0
Norma 1 (Python):  9.0


In [20]:
print("Norma 2 (propio): ", norma_vec(X, 2))
      
print("Norma 2 (Python): ", norm(X, 2))
      

Norma 2 (propio):  13.92838827718412
Norma 2 (Python):  13.928388277184121


In [21]:
print("Norma 10 (propio): ", norma_vec(X, 10))
      
print("Norma 10 (Python): ", norm(X, 10))
      

Norma 10 (propio):  9.300610567954676


ValueError: Invalid norm order for matrices.

In [22]:
print("Norma 95/7 (propio): ", norma_vec(X, 95/7))
      
print("Norma 95/7 (Python): ", norm(X, 95/7))

Norma 95/7 (propio):  9.141188057729725


ValueError: Invalid norm order for matrices.


Otra anomalía que debería eliminarsees el hecho de que se calcula la norma $-3$, cuando es algo que carece de sentido pues para que las normas $p$ sean efectivamente normas vectoriales se debe verificar que $p\ge1$ (aunque formalmente se puedan realizar los cálculos correspondientes). Proponemos mejorar la segunda versión nuestro programa para solucionar este problema.


In [23]:
print("Norma -3 (propio): ", norma_vec(x, -3))
      
print("Norma -3 (Python): ", norm(x, -3))

Norma -3 (propio):  Error norma_vec: valor de p.
Norma -3 (Python):  5.431641145211984


<b>Ejercicio 10:</b>Construir una función, a la que daremos el nombre de conv_norma_vec(), con un único argumento de entrada que es un vector o una matriz fila o columna. El objetivo de la función es el siguiente: en primer lugar calcula la norma infinita del mismo, y a continuación calcula las normas-p, con 𝑝=1,2,3,…, hasta que el error relativo de estas normas con la norma infinito sea, en valor absoluto, menor que un cierto 𝜀 fijado (por ejemplo 10−10). Dado que tenemos asegurada de forma teórica la convergencia de las normas-p hacia la norma-infinito, este proceso debe terminar en un momento dado. Considerar, por ejemplo, el vector x = array([1ek, 2ek, 3ek]) con 𝑘=0;±10;±100, y analizar los resultados obtenidos. Mejorar, si es posible, la función que calcula las normas vectoriales creada en el ejercicio anterior para solventar los problemas que aparecen. ¿Qué ocurre cuando se considera el vector nulo?

In [24]:
print("Convergencia de las normas vectoriales.")

X = array([[1], [2], [3]])
conv_norma_vec(X)

X = array([[1e10], [2e10], [3e10]])
conv_norma_vec(X)

X = array([[1e-10], [2e-10], [3e-10]])
conv_norma_vec(X)

X = array([[1e100], [2e100], [3e100]])
conv_norma_vec(X)

X = array([[1e-100], [2e-100], [3e-100]])
conv_norma_vec(X)

X = array([[0], [0], [0]])
conv_norma_vec(X)

Convergencia de las normas vectoriales.

 Vector: X =  [[1]
 [2]
 [3]]
Norma infinito =  3.0
Norma  1  =  6.0  Error relativo =  1.0
Norma  2  =  3.741657386773941  Error relativo =  0.24721912892464695
Norma  3  =  3.3019272488946267  Error relativo =  0.10064241629820891
Norma  4  =  3.1463462836457885  Error relativo =  0.04878209454859617
Norma  5  =  3.0773848853940624  Error relativo =  0.025794961798020804
Norma  6  =  3.0430102629193057  Error relativo =  0.014336754306435218
Norma  7  =  3.0246626009458444  Error relativo =  0.008220866981948127
Norma  8  =  3.014443335890572  Error relativo =  0.0048144452968572615
Norma  9  =  3.0085886861624296  Error relativo =  0.0028628953874765273
Norma  10  =  3.0051673034450284  Error relativo =  0.00172243448167612
Norma  11  =  3.003138080795621  Error relativo =  0.0010460269318737225
Norma  12  =  3.0019205304905707  Error relativo =  0.0006401768301902422
Norma  13  =  3.0011830869383065  Error relativo =  0.0003943623127688293
N