<div align="center"><span style="font-family: Arial,Helvetica,sans-serif; color:#0000FF""><b>
<span style="font-size: x-large">Métodos Numéricos II</span>
<br>
<span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2021/22</span>
<br>
<span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
<br>
<span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
<br>
<span style="font-size: small">Profs. María López Fernández y Francisco José Palma Molina (Área Conocimiento de Matemática Aplicada)</span>
<br>
<span style="font-size: medium; color:#FF0000">Práctica número 4</span>
</b></span></div>

In [68]:
from algoritmos import *

El objetivo de esta práctica es definir funciones <span style="font-family: Courier,monospace">Python</span> para resolver sistemas de ecuaciones lineales cuya matriz de coeficientes es triangular y que por tanto pueden ser resueltos mediante los <span style="color:#FF0000"><b>métodos de descenso</b></span> o de <b>sustitución progresiva</b> (en el caso de matrices triangulares inferiores) y los <span style="color:#FF0000"><b>métodos de remonte</b></span> o de <b>sustitución regresiva</b> (en el caso de matrices triangulares superiores).

Comenzamos por el caso de matrices triangulares inferiores, es decir, estudiamos los <span style="color:#FF0000"><b>métodos de descenso</b</span>.
<br><br>
Consideramos un sistema de $n$ ecuaciones lineales con $n$ incógnitas compatible y determinado $A\,X=B$, donde $A\in\mathcal{M}_n(\mathbb{K})$ es <b>trangular inferior</b> y $X,B\in\mathbb{K}^n$, es decir,
$$
\left( \begin{array}{cccc}
a_{1,1} & & & \\
a_{2,1} & a_{2,2} & & \\
\vdots & \vdots & \ddots & \\
a_{n,1} & a_{n,2} & \cdots & a_{n,n}
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{array} \right) = \left( \begin{array}{c}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{array} \right)\,.
$$
<br><br>
El carácter compatible y determinado del sistema implica que la matriz $A$ es regular y, por tanto, $a_{i,i}\ne0$, para todo $i=1,2,\ldots,n$.
<br><br>
Estos sistemas son fácilmente resolubles, pues al ser la matriz $A$ triangular inferior hace que se puedan calcular las incógnitas de manera inmediata, empezando por la primera y continuando hacia abajo; esto se conoce como <b>método de descenso</b> o de <b>sustitución progresiva</b>, y el algoritmo correspondiente es:

$$
\left\{ \begin{array}{ccl}
x_1 & = & \displaystyle \frac{1}{a_{1,1}}\,b_1 \\
x_i & = & \displaystyle \frac{1}{a_{i,i}}\,\left( b_i - \sum_{j=1}^{i-1} a_{i,j}\,x_j \right) \quad para \quad i=2,3,\ldots,n
\end{array} \right.
$$

Calcular la solución general de la ecuación diferencial
$$
\left( x + y^2 \right)\,dx - 2\,x\,y\,dy = 0\,.
$$ 
Elaborar un programa de nombre <span style="font-family: Courier,monospace">descenso()</span> que implemente el algoritmo del <b>método de descenso</b>. Esta función debe tener dos argumentos de entrada, que son la matriz $A$ y el segundo miembro $B$; por otro lado debe devolver también dos valores, siendo el primero de tipo booleano, en la que los valores <span style="font-family: Courier,monospace">True</span> o <span style="font-family: Courier,monospace">False</span> indican que se ha resuelto o no con éxito el sistema, y conteniendo el segundo valor la solución del sistema en caso de éxito o un mensaje de error en caso contrario.

In [69]:
def descenso(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q != 1:
        return False, "Error descenso: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error descenso: matriz singular."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, 1), dtype=complex)
    else:
        X = zeros((n, 1), dtype=float)
    for i in range(n):
        X[i, 0] = B[i, 0]
        if i != 0:
            X[i, 0] -= A[i, :i]@X[:i, 0]
        X[i, 0] = X[i, 0]/A[i, i]
    return True, X

<span style="color:#FF0000"><b>Comentarios.</b></span> Notamos que no se hace una <b>comprobación del carácter triangular</b> de la matriz $A$, trabajando con la parte triangular inferior e ignorando los elementos que puedan estar en la parte estrictamente triangular superior (que pueden o no ser ceros); esta estrategia se mostrará útil en algoritmos futuros que usen estas funciones como parte del código.
    <br><br>
    Los <b>casos de no éxito</b> en la resolución por el método de descenso se limitan a un problema con las dimensiones (bien porque la matriz $A$ no sea cuadrada, bien porque el segundo miembro $B$ no tenga las dimensiones adecuadas), o también a que la matriz $A$ sea singular o <i>casi singular</i>; el criterio de singularidad se establece en que $\displaystyle \min_{i=1,2,\ldots,n}|a_{i,i}|<10^{-200}$.
    <br><br>
    Finalmente, en los <b>casos de éxito</b> la solución $X$ será un vector de las dimensiones adecuadas de tipo real, excepto que alguno se los datos, $A$ o $B$, sea de tipo complejo, en cuyo caso será, evidentemente, de tipo complejo también.

**Ejercicio 2.** Comprobar el funcionamiento de la función elaborada resolviendo el sistema

$$

\left( \begin{array}{ccc}
1 & & \\
2 & 3 & \\
4 & 5 & 6
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array} \right) = \left( \begin{array}{c}
1 \\ 5 \\ 15
\end{array} \right)\,,

$$

cuya solución es el vector con sus tres componentes iguales a 1. Comprobar el resultado verificando que $B-A\,X=0$.

In [70]:
A = array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])
B = array([[1], [5], [15]])

descenso(A, B)


(True,
 array([[1.],
        [1.],
        [1.]]))

<span style="color:#FF0000"><b>Ejercicio 3.</b></span> Modificar el programa anterior para prever la posibilidad de <b>resolver simultáneamente varios sistemas lineales</b> $A\,X_r=B_r$, $r=1,2,\ldots,q$, todos con la misma matriz $A$ y diferentes segundos miembros $B_r$. Es por ello que el segundo argumento de entrada del programa $B$ no es necesariamente un vector columna, sino una matriz
$$
B = \left( B_1 | B_2 | \cdots | B_q \right) \in \mathcal{M}_{n\times q}(\mathbb{K})
$$
mientras que, en caso de éxito, la segunda salida del programa $X$ es también una matriz
$$
X = \left( X_1 | X_2 | \cdots | X_q \right) \in \mathcal{M}_{n\times q}(\mathbb{K})
$$
de las mismas dimensiones con las soluciones correspondientes.
    <br><br>
    En este sentido, recordamos que si $A\in\mathcal{M}_n(\mathbb{K})$ es una matriz invertible, el problema de <b>calcular su inversa</b> $A^{-1}$ es equivalente a resolver $n$ sistemas de ecuaciones lineales, todos con la misma matriz de coeficientes $A$. En efecto, si hacemos la descomposición por bloques de la matriz inversa
$$
A^{-1} = \left( X_1 | X_2 | \cdots | X_n \right)\,,
$$
y de la matriz identidad
$$
I = \left( E_1 | E_2 | \cdots | E_n \right)\,,
$$
entonces
$$
A\,A^{-1} = I \Leftrightarrow A\,X_i = E_i \quad para todo \quad i=1,2,\ldots,n\,.
$$
<br><br>
En general, utilizaremos esta técnica de resolver varios sistemas lineales de forma simultánea <b>siempre</b> que el algoritmo lo permita.
</span>

In [71]:
# A rellenar.
def descenso1(A, B):
    (m, n) = shape(A)
    (p, q) = shape(B)
    if m != n or n != p or q < 1:
        return False, "descenso: error en las dimensiones"
    #if min(abs(diag(A))) < 1e-100:
    #    return False, "descenso: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
            X[i, :] = X[i, :] - A[i, :i]@X[:i, :]
        #X[i, :] = X[i, :]/A[i, i]
    return True, X
    

<span style="color:#FF0000"><b>Ejercicio 4.</b></span> Comprobar el funcionamiento de la modificación realizada en el programa calculando la inversa de la matriz
$$
A = \left( \begin{array}{ccc}
1 & & \\
2 & 3 & \\
4 & 5 & 6
\end{array} \right)\,.
$$
Comprobar también el resultado verificando que $A\,A^{-1}=I$.
    </span>

In [72]:
A = array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])

b =descenso1(A, eye(3))

Consideramos ahora el caso de matrices triangulares superiores, es decir, estudiamos los <span style="color:#FF0000"><b>métodos de remonte</b></span>.
<br><br>
Consideramos un sistema de $n$ ecuaciones lineales con $n$ incógnitas compatible y determinado $A\,X=B$, donde $A\in\mathcal{M}_n(\mathbb{K})$ es <b>triangular superior</b> y $X,B\in\mathbb{K}^n$, es decir,
$$
\left( \begin{array}{cccc}
a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
& a_{2,2} & \cdots & a_{2,n} \\
& & \ddots & \vdots \\
& & & a_{n,n}
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{array} \right) = \left( \begin{array}{c}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{array} \right)\,.
$$
<br><br>
Aquí también el carácter compatible y determinado del sistema implica que la matriz $A$ es regular y, por tanto, $a_{i,i}\ne0$, para todo $i=1,2,\ldots,n$.
<br><br>
Estos sistemas son fácilmente resolubles, pues al ser la matriz $A$ triangular superior hace que se puedan calcular las incógnitas de manera inmediata, empezando ahora por la última y continuando hacia arriba; esto se conoce como <b>método de remonte</b> o de <b>sustitución regresiva</b>, y el algoritmo correspondiente es:
$$
\left\{ \begin{array}{ccl}
x_n & = & \displaystyle \frac{1}{a_{n,n}}\,b_n \\
x_i & = & \displaystyle \frac{1}{a_{i,i}}\,\left( b_i - \sum_{j=i+1}^n a_{i,j}\,x_j \right) \quad para \quad i=n-1,n-2,\ldots,1
\end{array} \right.
$$
</span>


<span style="color:#FF0000"><b>Ejercicio 5.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">remonte()</span> que implemente el algoritmo del <b>método de remonte</b>. Esta función debe tener las mismas características que el programa <span style="font-family: Courier,monospace">descenso()</span>.
    <br><br>
    <span style="color:#FF0000"><b>Comentario.</b></span> Para generar un contador que retroceda, se puede utilizar la instrucción <span style="font-family: Courier,monospace">range(a,b,c)</span> que genera una lista de enteros desde <span style="font-family: Courier,monospace">a</span> (incluido) hasta <span style="font-family: Courier,monospace">b</span> (excluido), con salto de <span style="font-family: Courier,monospace">c</span> (que puede ser negativo).
    </span>

In [73]:
# A rellenar
def remonte(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error remonte: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error remonte: matriz singular."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n):
        for k in range (q): 
            j=n-1-i
            X[j, k] = B[j, k]
            if i != k:
                X[j, k] -= A[j, (j+1):n]@X[(j+1):n, k]
            X[j, k] = X[j, k]/A[j, j]
    return True, X
    

<span style="color:#FF0000"><b>Ejercicio 6.</b></span> 

Comprobar el funcionamiento de la función elaborada resolviendo el sistema
$$
\left( \begin{array}{ccc}
1 & 2 & 3\\
& 4 & 5 \\
& & 6
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array} \right) = \left( \begin{array}{c}
6 \\ 9 \\ 6
\end{array} \right)\,,
$$
cuya solución es el vector con sus tres componentes iguales a 1. Calcular también la inversa de la matriz de coeficientes. Comprobar los resultados obtenidos.


In [74]:
A = array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
B = array([[6], [9], [6]])

remonte(A, B)

(True,
 array([[1.],
        [1.],
        [1.]]))

<span style="color:#FF0000"><b>Problema.</b></span> Resolver los siguientes sistemas de ecuaciones lineales:
$$
\begin{array}{lllll}
(a) & \left( \begin{array}{rrrr}
5 & & & \\ 1 & 3 & & \\ 3 & 4 & 2 & \\ -1 & 3 & -6 & -1
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
-10 \\ 4 \\ 2 \\ 5
\end{array} \right) &
(b) & \left( \begin{array}{rrrr}
2 & & & \\ -1 & 4 & & \\ 3 & -2 & -1 & \\ 1 & -2 & 6 & 3
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
6 \\ 5 \\ 4 \\ 2
\end{array} \right) \\
 \\
(c) & \left( \begin{array}{rrrr}
4 & -1 & 2 & 3 \\ & -2 & 7 & -4 \\ & & 6 & 5 \\ & & & 3
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
20 \\ -7 \\ 4 \\ 6
\end{array} \right) &
(d) & \left( \begin{array}{rrrr}
3 & -2 & 1 & -1 \\ & 4 & -1 & 2 \\ & & 2 & 3 \\ & & & 5
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
8 \\ -3 \\ 11 \\ 15
\end{array} \right)
\end{array}
$$
<br><br>
Como tarea adicional se pide:
<ul>
    <li> comprobar la exactitud de los resultados obtenidos;</li>
    <li> calcular las inversas de las matrices de coeficientes y comprobar la exactitud de los resultados;</li>
    <li> en algún caso, cambiar alguna dimensión en la matriz de coeficientes o en el segundo miembro, de manera que se provoque una situación de error;</li>
    <li> el algún caso, cambiar a 0 (o a un número muy próximo a 0) el valor de un elemento diagonal de la matriz de coeficientes, de manera que se provoque una situación de error;</li>
    <li> en algún caso, cambiar el valor de algunos de los elementos que deben ser 0 en una matriz triangular, por otros valores distintos de 0 de manera que la matriz deje de ser triangular; observar como los programas obvian estos valores y resuelven los sistemas como si las matrices fueran triangulares (si se hace la comprobación de la exactitud de los resultados se detectará este problema);</li>
    <li> cambiar algunos de los elementos de la matriz de coeficientes y/o del segundo miembro por números complejos para comprobar que los programas funcionan con aritmética compleja.</li>
</ul>

In [75]:
# Problema a.
A = array([[5, 0, 0, 0], [1, 3, 0, 0], [3, 4, 2, 0], [-1, 3, -6, -1]])
B = array([[-10], [4], [2], [5]])

descenso(A, B)
#print(inv(A)@B)


(True,
 array([[-2.],
        [ 2.],
        [ 0.],
        [ 3.]]))

In [76]:
# Problema c.
A = array([[4, -1, 2, 3], [0, -2, 7, -4], [0, 0, 6, 5], [0, 0, 0, 3]])
B = array([[20], [-7], [4], [6]])

remonte(A, B)
# print(inv(A)@B)


(True,
 array([[ 3.],
        [-4.],
        [-1.],
        [ 2.]]))


<span style="color:#FF0000"><b>Ejercicio 7.</b></span> Elaborar dos nuevas funciones, a las que daremos el nombre de <span style="font-family: Courier,monospace">descenso1()</span> y <span style="font-family: Courier,monospace">remonte1()</span>, respectivamente, que implementen los mismos <b>métodos de descenso y remonte</b>, pero suponiendo ahora que la matriz de coeficientes $A$ tiene <b>1 en la diagonal principal</b> (independientemente de los valores que estén guardados en los elementos diagonales de la matriz que se pasa como argumento a las funciones creadas). Estos programas serán de utilidad en la fase final de resolución de un sistema lineal por métodos de descomposición.
<br><br>
<span style="color:#FF0000"><b>Comentario.</b></span> Para realizar los programas anteriores, únicamente hay que tener en cuenta que los elementos diagonales de las matrices solamente aparecen en la división final del algoritmo, por lo que <i>suprimir esa división</i> es equivalente a <i>dividir por 1</i>. Por otro lado no será necesario en este caso la comprobación sobre el carácter regular de la matriz, puesto que estamos suponiendo que los elementos diagonales valen 1 (independientemente de los valores que se encuentren almacenados en dichas posiciones) y por tanto la matriz es siempre inversible.
    

In [77]:
# A rellenar.
def descenso1(A, B):
    (m, n) = shape(A)
    (p, q) = shape(B)
    if m != n or n != p or q < 1:
        return False, "descenso: error en las dimensiones"
    #if min(abs(diag(A))) < 1e-100:
    #    return False, "descenso: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
            X[i, :] = X[i, :] - A[i, :i]@X[:i, :]
        #X[i, :] = X[i, :]/A[i, i]
    return True, X    

In [78]:
# A rellenar.
def remonte1(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error descenso: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error descenso: matriz singular."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n-1 , -1 ,-1): #Desde n-1 hasta 0 con salto -1  (ponemos -1 porque el -1 no está incluido, para en 0) 
        X[i, :] = B[i, :]
        if i != n-1:
            X[i, :] -= A[i, i+1:]@X[i+1:, :]
    return True, X

<span style="color:#FF0000"><b>Ejercicio 8.</b></span> Resolver los siguientes sistemas de ecuaciones lineales:
$$
\begin{array}{lllll}
(a) & \left( \begin{array}{rrrr}
1 & & & \\ 1 & 1 & & \\ 3 & 4 & 1 & \\ -1 & 3 & -6 & 1
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
-10 \\ 4 \\ 2 \\ 5
\end{array} \right) &
(b) & \left( \begin{array}{rrrr}
1 & -1 & 2 & 3 \\ & 1 & 7 & -4 \\ & & 1 & 5 \\ & & & 1
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
20 \\ -7 \\ 4 \\ 6
\end{array} \right)
\end{array}
$$
<br><br>
Dado que ambas matrices tienes elementos diagonales iguales a 1, resolver los sistemas utilizando tanto los métodos generales de <span style="font-family: Courier,monospace">descenso()</span> y <span style="font-family: Courier,monospace">remonte()</span>, respectivamente, como los métodos modificados de <span style="font-family: Courier,monospace">descenso1()</span> y <span style="font-family: Courier,monospace">remonte1()</span>, viendo que se obtienen los mismos resultados.


In [79]:
A = array([[1, 0, 0, 0], [1, 1, 0, 0], [3, 4, 1, 0], [-1, 3, -6, 1]])
B = array([[-10], [4], [2], [5]])

descenso1(A, B)


(True,
 array([[ -10.],
        [  14.],
        [ -24.],
        [-191.]]))

In [80]:
A = array([[1, -1, 2, 3], [0, 1, 7, -4], [0, 0, 1, 5], [0, 0, 0, 1]])
B = array([[20], [-7], [4], [6]])

remonte1(A, B)

(True,
 array([[253.],
        [199.],
        [-26.],
        [  6.]]))


Otro caso particularmente interesante se produce cuando la <b>matriz triangular</b> $A$ es, al mismo tiempo, <b>tridiagonal</b>, lo que significa que realmente sus únicos elementos no nulos pueden estar situados en dos diagonales: la diagonal principal y una diagonal adicional, bien la sub-diagonal en el caso de triangulares inferiores, bien la supra-diagonal en el caso de triangulares superiores. Una <b>resolución óptima</b> de estos sistemas evita aquellos cálculos inútiles al involucrar los muchos 0 que existen.


<span style="color:#FF0000"><b>Ejercicio 9.</b></span> Elaborar dos nuevas funciones, a las que daremos el nombre de <span style="font-family: Courier,monospace">descenso_1diag()</span> y <span style="font-family: Courier,monospace">remonte_1diag()</span>, respectivamente, que implementen la <b>mejora de tiempo de cálculo</b> descrita en el párrafo anterior para <b>matrices triangulares y tridiagonales</b>. Estos programas serán similares a los anteriores en cuanto a argumentos de entrada y de salida y tampoco harán una comprobación sobre el carácter tridiagonal de la matriz, suponiendo que son nulos los elementos que deben serlo, independientemente de los valores que estén guardados en dichas posiciones de la matriz.

In [81]:
# A rellenar.
def descenso_1diag(A, B):
    (m, n) = shape(A)
    (p, q) = shape(B)
    if m != n or n != p or q < 1:
        return False, "descenso: error en las dimensiones"
    if min(abs(diag(A))) < 1e-100:
        return False, "descenso: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
            X[i, i] = X[i, i] - A[i, i-1]*X[i-1, :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X

In [ ]:
# A rellenar.
def remonte_1diag(A, B):
    (m, n) = shape(A)
    (p, q) = shape(B)
    if m != n or n != p or q < 1:
        return False, "remonte: error en las dimensiones"
    if min(abs(diag(A))) < 1e-100:
        return False, "remonte: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n-1,-1,-1):
        X[i, :] = B[i, :]
        if i != n-1:
            X[i, :] = X[i, :] - A[i, i+1:]@X[i+1:, :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X


<span style="color:#FF0000"><b>Ejercicio 10.</b></span> Crear una matriz de orden 5, triangular inferior (superior) y tridiagonal, que tenga en la diagonal principal 2 y en la sub-diagonal (supra-diagonal) $-1$; crear igualmente un segundo miembro adecuado para que la solución del sistema lineal correspondiente sea el vector con todos sus elementos igual a 1 (esto se consigue tomando como segundo miembro el vector cuyos elementos son las sumas de los elementos de las filas correspondientes de la matriz de coeficientes).
<br><br>
Resolver ese sistema lineal con la función que implementa el método de descenso (remonte) completo y el que implementa el método correspondiente optimizado para matrices tridiagonales, comprobando que se obtienen resultados similares.

In [85]:
A = 2*eye(5) + diag([-1,-1,-1, -1], k=-1)
print(A)
B = [1, 1, 1, 1]

descenso(A, B)


[[ 2.  0.  0.  0.  0.]
 [-1.  2.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.]
 [ 0.  0. -1.  2.  0.]
 [ 0.  0.  0. -1.  2.]]


ValueError: not enough values to unpack (expected 2, got 1)

In [86]:
A = 2*eye(5) + diag([-1,-1,-1, -1], k=-1)
B = inv(A)

print(B)


[[0.5     0.      0.      0.      0.     ]
 [0.25    0.5     0.      0.      0.     ]
 [0.125   0.25    0.5     0.      0.     ]
 [0.0625  0.125   0.25    0.5     0.     ]
 [0.03125 0.0625  0.125   0.25    0.5    ]]


<span style="color:#FF0000"><b>Ejercicio 11.</b></span> Calcular las inversas de las matrices del ejercicio anterior, comprobando que dichas inversas no conservan el carácter tridiagonal de la matriz inicial.

In [ ]:
A = 2*eye(5) ...
B = ...


In [ ]:
A = 2*eye(5) ...
B = ...



<span style="color:#FF0000"><b>Ejercicio 12.</b></span> Se puede <b>controlar el tiempo de ejecución</b> de un programa importando la función <span style="font-family: Courier,monospace">time()</span> del módulo <span style="font-family: Courier,monospace">time</span>, haciendo una llamada a dicha función antes y después de ejecutar el programa que queramos controlar y calculando la diferencia de tiempos.
<br><br>
Analizar la diferencia de tiempos de ejecución de la versión general del programa <span style="font-family: Courier,monospace">descenso()</span> (respect. <span style="font-family: Courier,monospace">remonte()</span>) y del programa <span style="font-family: Courier,monospace">descenso_1diag()</span> (respect. <span style="font-family: Courier,monospace">remonte_1diag()</span>), usando un sistema lineal análogo al del Ejercicio 10, pero de tamaño tan grande como sea posible.

In [87]:
from time import time
n = 10000
A = 2*eye(5) + diag([-1,-1,-1, -1], k=-1)
B = [1, 1, 1, 1, 1]
#
tiempo_ini = time()
exito, X = descenso(A, B)
tiempo_fin = time()


ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
from time import time
n = 10000
A = 2*eye(n) ...
B = ...



<span style="color:#FF0000"><b>Ejercicio 13.</b></span> Al igual que para las matrices triangulares y tridiagonales (es decir, matrices banda con semi-anchura de la banda $r=1$) hemos elaborado funciones optimizadas de los algoritmos de descenso y de remonte respectivamente, elaborar funciones similares para el caso de <b>matrices banda con semi-anchura de la banda $r$</b> ($1\le r<n$).
<br><br>
Utilizar los nombres de <span style="font-family: Courier,monospace">descenso_rdiag()</span> y <span style="font-family: Courier,monospace">remonte_rdiag()</span> para dichas funciones, que deben tener un parámetro de entrada adicional que es justamente el valor de $r$.
<br><br>
Observamos que en el caso $r=n-1$ la matriz es realmente llena, si bien el carácter de matriz banda se utiliza cuando $r$ es <i>pequeño<i> en comparación con $n$.

In [ ]:
# A rellenar.
def descenso_rdiag(A, B, r):
    

In [ ]:
# A rellenar.
def remonte_rdiag(A, B, r):
    


<span style="color:#FF0000"><b>Ejercicio 14.</b></span> Crear una matriz de orden 5, pentadiagonal inferior (superior) y tridiagonal, que tenga en la diagonal principal 4 y en las dos sub-diagonales (supra-diagonales) $-1$; crear igualmente un segundo miembro adecuado para que la solución del sistema lineal correspondiente sea el vector con todos sus elementos igual a 1.
<br><br>
Resolver ese sistema lineal con la función que implementa el método de descenso (remonte) completo y el que implementa el método correspondiente optimizado para matrices $r$-bandas, comprobando que se obtienen resultados similares.

In [ ]:
A = 4*eye(5) ...
B = ...


In [ ]:
A = 4*eye(5) ...
B = ...


<span style="color:#FF0000"><b>Comentario.</b></span> Consideremos de nuevo el caso de una matriz invertible $A\in\mathcal{M}_n(\mathbf{K})$ triangular inferior y tridiagonal. Es habitual que para el <b>almacenamiento</b> de la misma en la memoria del ordenador, no se utilice una matriz de tamaño $n\times n$ (cuyos elementos serían en su mayoría 0), sino que se utilice una <i>matriz optimizada</i> de tamaño $n\times2$, en cuya segunda columna se almacenan los elementos de la diagonal principal conservando la fila, y en cuya primera columna se almacenan los elementos de la sub-diagonal también conservando la fila (el valor almacenada en la primera fila y primera columna de esta <i>matriz optimizada</i> no tiene ninguna utilidad en este caso). En el caso de matrices triangulares superiores se almacena la diagonal principal en la primera columna, mientras que en la segunda columna se almacenan los elementos de la supra-diagonal, siempre conservando la fila (en este caso el valor almacenado en la segunda columna de la última fila no tiene ninguna utilidad).
<br><br>
Otras técnicas similares se utilizan, en general, para el almacenamiento de <b>matrices vacías</b>.

<span style="color:#FF0000"><b>Ejercicio 15.</b></span> Modificar nuestro programa <span style="font-family: Courier,monospace">descenso_1diag()</span> creando un nuevo programa de nombre <span style="font-family: Courier,monospace">descenso_1diag_vacia()</span> que tenga en cuenta esta forma optimizada de almacenamiento de la matriz. Realizar un análisis similar para el caso de matrices triangulares superiores, pasando del programa <span style="font-family: Courier,monospace">remonte_1diag()</span> al programa <span style="font-family: Courier,monospace">remonte_1diag_vacia()

In [ ]:
# A rellenar.
def descenso_1diag_vacia(A, B):
    

In [ ]:
# A rellenar.
def remonte_1diag_vacia(A, B):
    

<span style="color:#FF0000"><b>Ejercicio 16.</b></span> Crear una matriz de orden $n$ (con $n$ suficientemente grande), triangular inferior (superior) y tridiagonal, que tenga en la diagonal principal 2 y en la sub-diagonal (supra-diagonal) $-1$; crear igualmente un segundo miembro adecuado para que la solución del sistema lineal correspondiente sea el vector con todos sus elementos igual a 1.
<br><br>
Resolver ese sistema lineal con la función que implementa el método de descenso (remonte) completo, el que implementa el método de descenso (remonte) optimizado para matrices triadiagonales y el que implementa el método correspondiente optimizado para matrices tridiagonales y para el almacenamiento optimizado de la matriz, comprobando que se obtienen resultados similares.

In [ ]:
from time import time
n = 10000
A = 2*eye(n) ...
A_vacia = zeros((n,2))
A_vacia[:, 0] = -1
A_vacia[:, 1] = 2
B = ...


In [ ]:
from time import time
n = 10000
A = 2*eye(n) ...
A_vacia = zeros((n,2))
A_vacia[:, 0] = 2
A_vacia[:, 1] = -1
B = ...
