In [1]:
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *

**Ejercicio 1.**
Se considera el sistema lineal $AX=B$, donde:

$$A=\begin{pmatrix}
10 & 1 & 4 & 0\\
1 & 10 & 5 & -1\\
4 & 5 & 10 & 7\\
0 & -1 & 7 & 9 
\end{pmatrix}
\quad \text{y} \quad
B=\begin{pmatrix}
15 \\
15\\
26\\
15
\end{pmatrix}$$

**a)**
Al aplicar el método de Gauss con estrategia de pívot parcial al sistema anterior, se obtiene un sistema triangular
superior equivalente, que posteriormente se resuelve mediante un proceso de remonte. Escribir dicho sistema
triangular superior y la solución del sistema.

In [5]:
A = array([[10, 1, 4, 0], [1, 10, 5, -1], [4, 5, 10, 7], [0, -1, 7, 9]])
print("A:")
print(A)

B = array([[15], [15], [26], [15]])
print("B:")
print(B)

exito, X = gauss_pp(A, B)

if exito:
    print("La solucion al sistema es X")
    print(X)
    MA, MB = gauss_pp2(A, B)
    print("La matriz triangular superior es: MA")
    print(triu(MA))
    print("La B asociada es: MB")
    print(MB)
    print()
else:
    print("No se ha podido resolver el sitema")

A:
[[10  1  4  0]
 [ 1 10  5 -1]
 [ 4  5 10  7]
 [ 0 -1  7  9]]
B:
[[15]
 [15]
 [26]
 [15]]
La solucion al sistema es X
[[1.]
 [1.]
 [1.]
 [1.]]
La matriz triangular superior es: MA
[[ 1.00000000e+01  1.00000000e+00  4.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  9.90000000e+00  4.60000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.46464646e+00  8.89898990e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.35317997e-03]]
La B asociada es: MB
[[ 1.50000000e+01]
 [ 1.35000000e+01]
 [ 1.63636364e+01]
 [-1.35317997e-03]]



---

**b)**
Calcular la inversa de A mediante el método de Gauss con estrategia de pívot parcial.

In [7]:
I = eye(shape(A)[0])
print("\nCalculamos la inversa de A sabiendo que es la solucion del sistema AX=I:")
e, X= gaussjordan_pp(A,I)

print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Calculamos la inversa de A sabiendo que es la solucion del sistema AX=I:
[[ 105.  167. -304.  255.]
 [ 167.  266. -484.  406.]
 [-304. -484.  881. -739.]
 [ 255.  406. -739.  620.]]


-----

**c)**
Escribir, si es posible, la factorización LU de la matriz A.

In [10]:
exit, LU = facto_lu(A)
if exito:
    print("La factorizacion es posible")
    print("La matriz L es: ")
    print(tril(LU, k=-1) + eye(4))  #eye(shape(A)[0])
    print(triu(LU))


La factorizacion es posible
La matriz L es: 
[[ 1.          0.          0.          0.        ]
 [ 0.1         1.          0.          0.        ]
 [ 0.4         0.46464646  1.          0.        ]
 [ 0.         -0.1010101   1.19193548  1.        ]]
[[ 1.00000000e+01  1.00000000e+00  4.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  9.90000000e+00  4.60000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  6.26262626e+00  7.46464646e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.61290323e-03]]


----

**d)**
Se considera ahora el sistema perturbado $A\bar{X}=\bar{B}$, donde $\bar{X}= X +δX$ y $\bar{B}= B +δB$ , siendo $δB=(1,  1,  −1,  1)^t$.
Calcular la solución del sistema perturbado y hacer el análisis numérico (en norma 2) de la situación propuesta,
comprobando que el error relativo de la solución es menor o igual que el producto del condicionamiento por el
error relativo de los datos.

Es decir resolvamos la siguiente desigualdad:

$$\frac{\|\delta X\|_2}{\|X\|_2}\leq \text{cond}_2(A) \frac{\|\delta B\|_2}{\|B\|_2}$$

In [11]:
print("\nLa matriz A es:")
A = array([[10, 1, 4, 0], [1, 10, 5, -1], [4, 5, 10, 7], [0, -1, 7, 9]])
print(A)

print("\nEl segundo miembro es:")
B = array([[15], [15], [26], [15]])
print(B)

print("\nLa matriz identidad es:")
I = eye(shape(A)[0])
print(I)

print("\nLa diferencia del segundo miembro dB es:")
dB = array([[1], [1], [-1], [1]])
print(dB)

##Calculamos Bper sabiendo que Bper = B + dB

print("\nEl segundo miembro del sistema perturbado es:")
Bper = B + dB
print(Bper)


##Calculemos la solucion del sistema AX=B
print("\nLa solución del sistema AX = B es:")
e, X = gauss_pp(A, B)
print(X)

##Calculemos la solucion del sistema perturbado AXper=Bper
print("\nLa solución del sistema AX = B_ es:")
e, Xper = gauss_pp(A, Bper)
print(Xper)

##Calculemos la inversa de A
e, iA = gauss_pp(A, I)  # se podria hacer con inv(A)
print("\nLa inversa de A es:")
print(iA)

##Calculemos el condicionamiento_2 de A
print("\nEl condicionamiento de la matriz A es:")
cond = norma_mat(A, 2)*norma_mat(iA, 2)
condM  =cond = norma_mat(A, 2)*norma_mat(inv(A), 2)
print(cond)
print(condM)

##Calculemos dX sabiendo que Xper = X + dX

dX = Xper - X

print("\nEl incremento de las soluciones es:")
print(dX)

print("\nYa tenemos caracterizados todos los elementos de las desigualdades, ahora veamos si se prueba la desigualdad.")

##Llamaremos izq a los elementos de la izquierda de la desigualdad.

izq = norma_vec(dX, 2)/norma_vec(X, 2)

##Llamaremos der a los elementos de la derecha de la desigualdad.

der = cond*(norma_vec(dB, 2)/norma_vec(B, 2))

if (izq <= der):
    print("\nLa desigualdad si se cumple.")
else:
    print("\nLa desigualdad no se cumple.")


La matriz A es:
[[10  1  4  0]
 [ 1 10  5 -1]
 [ 4  5 10  7]
 [ 0 -1  7  9]]

El segundo miembro es:
[[15]
 [15]
 [26]
 [15]]

La matriz identidad es:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

La diferencia del segundo miembro dB es:
[[ 1]
 [ 1]
 [-1]
 [ 1]]

El segundo miembro del sistema perturbado es:
[[16]
 [16]
 [25]
 [16]]

La solución del sistema AX = B es:
[[1.]
 [1.]
 [1.]
 [1.]]

La solución del sistema AX = B_ es:
[[  832.]
 [ 1324.]
 [-2407.]
 [ 2021.]]

La inversa de A es:
[[ 1.05000000e+02 -4.11589508e+00 -3.52400000e+02  0.00000000e+00]
 [ 1.67000000e+02  4.11048236e+01  0.00000000e+00  4.06000000e+02]
 [-3.04000000e+02  1.35317997e-02  8.81000000e+02 -7.39000000e+02]
 [ 2.55000000e+02  4.06000000e+02 -7.39000000e+02  6.20000000e+02]]

El condicionamiento de la matriz A es:
35792.397628825755
35792.397628825755

El incremento de las soluciones es:
[[  831.]
 [ 1323.]
 [-2408.]
 [ 2020.]]

Ya tenemos caracterizados todos los elementos de las desiguald

----