# Exámen 2020 

In [1]:
# Cargamos los módulos necesarios
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *

Resolver el sistema AX = B mediante el método de Gauss-Jordan con estrategia
de pivot parcial. Escribir ademas las matrices MA y MB resultantes tras el
método mencionado.

Calcular, si existe, la matriz L de las factorización LU de A.
Calcular la inversa de la matriz A.
Se considera ahora el sistema perturbado AX' = B'

In [4]:
A = array([[-33,36,-27,18,-9], [-33,51,-45,30,-15], [-19,38,-45,34,-17], [-9,18,-27,27,-15], [-3,6,-9,12,-9]])
B = array([[120], [186], [162], [99], [36]])

e, X = gaussjordan_pp(A,B)

print("La solcuión del sistema AX = B es X = ")
print(X)
print()

print('''Para escribir las matrices MA y MB vamos a modificar la funcion 
gaussjordan_pp. En dicha función, se van creando las matrices MA y MB 
tras cada iteracion, en dicha funcion en la iteración final, gjA = triu(MA) 
(pues en dicha matriz se guardan mas cosas además de la matriz MA) y gjB = MB)''')
print()

def gaussjordan_pp2(A, B):
    (m, n) = shape(A)
    (p, q) = shape(B)
    if m != n or n != p or q < 1:
        return False, "gaussjordan_pp: error en las dimensiones"
    if A.dtype == complex or B.dtype == complex:
        gjA = array(A, dtype=complex)
        gjB = array(B, dtype=complex)
    else:
        gjA = array(A, dtype=float)
        gjB = array(B, dtype=float)
    for k in range(n):
        pos = argmax(abs(gjA[k:n, k]))
        ik = pos+k
        if ik != k:
            gjA[[ik, k], :] = gjA[[k, ik], :]
            gjB[[ik, k], :] = gjB[[k, ik], :]
        if abs(gjA[k, k]) >= 1e-15:
            for i in range(k):
                gjA[i, k] = gjA[i, k]/gjA[k, k]
                gjA[i, k+1:] = gjA[i, k+1:]-gjA[i, k]*gjA[k, k+1:]
                gjB[i, :] = gjB[i, :]-gjA[i, k]*gjB[k, :]
            for i in range(k+1, n):
                gjA[i, k] = gjA[i, k]/gjA[k, k]
                gjA[i, k+1:] = gjA[i, k+1:]-gjA[i, k]*gjA[k, k+1:]
                gjB[i, :] = gjB[i, :]-gjA[i, k]*gjB[k, :]
    if min(abs(diag(gjA))) < 1e-15:
        return False, "gaussjordan_pp: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n):
        X[i, :] = gjB[i, :]/gjA[i, i]
    return True, gjA, gjB

e, MA, MB = gaussjordan_pp2(A,B)
print("La matria MA es: ")
print(triu(MA))
print()
print("La matriz MB es: ")
print(MB)
print()

print('''La funcion facto_lu devuelve en una misma matriz la matriz L y 
la matriz U. La matriz L es la matriz triangular inferior con unos en la 
diagonal, por tanto debemos quedarnos con la parte escrictamente triangular
inferior y sumarle la diagonal llena de unos''')
print()
e, LU = facto_lu(A)
L = tril(LU, k = -1) + eye(5)
print("La matriz L de la factorización LU es L: ")
print(L)
print()

U = triu(LU)
print("La matriz U de la factorización LU es U: ")
print(U)
print()

print("La inversa de la matriz A es:")
invA = inv(A)
print(invA)
print()

B_ = array([[119], [187], [162], [100], [35]])
deltaB = B_ - B

e, X_ = gaussjordan_pp(A,B_)
deltaX = X_ - X

izquierda = norma_vec(deltaX, inf)/norma_vec(X, inf)
derecha = norma_mat(A, inf)*norma_mat(invA,inf)*norma_vec(deltaB, inf)/norma_vec(B, inf)

print("La desigualdad es",izquierda <= derecha)

La solcuión del sistema AX = B es X = 
[[1.]
 [4.]
 [2.]
 [5.]
 [3.]]

Para escribir las matrices MA y MB vamos a modificar la funcion 
gaussjordan_pp. En dicha función, se van creando las matrices MA y MB 
tras cada iteracion, en dicha funcion en la iteración final, gjA = triu(MA) 
(pues en dicha matriz se guardan mas cosas además de la matriz MA) y gjB = MB)

La matria MA es: 
[[-33.           2.08421053   4.5375       1.65        -1.65      ]
 [  0.          17.27272727  -3.88636364  -2.11111111   2.11111111]
 [  0.           0.           7.57894737  -1.89473684   1.89473684]
 [  0.           0.           0.           4.5          2.5       ]
 [  0.           0.           0.           0.          -1.5       ]]

La matriz MB es: 
[[-33.        ]
 [ 69.09090909]
 [ 15.15789474]
 [ 22.5       ]
 [ -4.5       ]]

La funcion facto_lu devuelve en una misma matriz la matriz L y 
la matriz U. La matriz L es la matriz triangular inferior con unos en la 
diagonal, por tanto debemos quedarnos 

Obtener toda la informacion que sea posible sobre los autovalores de la matriz
A, utilizando única y exclusivamente el método de la potencia, el método de l
potencia inversa y el método de la potencia desplazada inversa con desplazamiento de 9, en los tres casos tomando como vector inicla el primer vector de la base canónica. Indicar tamién la localización de los autovaloores que aún faltan a partir de esos datos. Se valorará positivamente la corrección de los razonamientos a partir de la información disponible.

Sea A_ la matriz cuyos elementos son iguales a los de A, excepto el de la primera fila y quinta columna que ahora vale -10. Calcular el autovalor dominante de A_ y compprobar si se verifica el teorema de Bauer-Fike para dicho autovalor.

In [11]:
A = array([[-33,36,-27,18,-9], [-33,51,-45,30,-15], [-19,38,-45,34,-17], [-9,18,-27,27,-15], [-3,6,-9,12,-9]])
X0 = array([[1], [0], [0], [0], [0]])
exito, normas, lambdas, X  = potencia(A, X0, inf, 200, 1e-8)

# print(eig(A)[0]) # Los autovalores son [ 12.   6. -15.  -9.  -3.]
print()
print("\n Método de la potencia con norma inf.")
if exito:
    print("Convergencias de las normas: \n" ,normas)
    print("Convergencias de los cocientes: \n" ,lambdas)
    print("Convergencias de los vectores: \n" ,X)
    
print("De lo que deducimos que -15 es autovalor de A")

exito, normas, lambdas, X  = potenciainv(A, X0, inf, 200, 1e-8)
print()
print("\n Método de la potencia inversa con norma inf.")
if exito:
    print("Convergencias de las normas: \n" ,normas)
    print("Convergencias de los cocientes: \n" ,lambdas)
    print("Convergencias de los vectores: \n" ,X)
print("De lo que deducimos que -1/3 es autovalor de inv(A), luego -3 es autovalor de A")
    
exito, normas, lambdas, X  = potenciadesinv(A, X0, 9, inf, 200, 1e-8)
print()
print("\n Método de la potencia inversa desplazada por 9 inversa con norma inf.")
if exito:
    print("Convergencias de las normas: \n" ,normas)
    print("Convergencias de los cocientes: \n" ,lambdas)
    print("Convergencias de los vectores: \n" ,X)
    
print("De lo que deducimos que 3 + 9 es autovalor de A, luego 12 es autovalor de A")
print()
print('''Tenemos entonces que el mayor autovalor es 15 y el menos autovalores es -3. Sean
a y b los autovalores que faltan por calcular. Entonces a y b se encuentran en el intervalo
[-3, 15]
''')


 Potencia: convergencia numérica alcanzada.


 Método de la potencia con norma inf.
Convergencias de las normas: 
 14.999999995703138
Convergencias de los cocientes: 
 [-15.        +0.j -14.99999998+0.j  11.99995483+0.j   0.        +0.j
   0.        +0.j]
Convergencias de los vectores: 
 [[ 1.00000000e+00]
 [ 5.00000000e-01]
 [-1.27314069e-10]
 [ 2.53693993e-16]
 [ 1.22380271e-16]]
De lo que deducimos que -15 es autovalor de A

 Potenciainv: convergencia numérica alcanzada.


 Método de la potencia inversa con norma inf.
Convergencias de las normas: 
 0.3333333351959784
Convergencias de los cocientes: 
 [ 0.        +0.j -0.11129419+0.j  0.16667644+0.j -0.33333334+0.j
 -0.33333334+0.j]
Convergencias de los vectores: 
 [[-3.76754366e-17]
 [-2.18811844e-14]
 [-1.86268879e-09]
 [-5.00000003e-01]
 [-1.00000000e+00]]
De lo que deducimos que -1/3 es autovalor de inv(A), luego -3 es autovalor de A

 Potenciainv: convergencia numérica alcanzada.


 Método de la potencia inversa desplazada por 