 <center><span style="font-variant:small-caps;font-family: Times New Roman, Times, serif;"><font size="6">Métodos Numéricos II</font></span></center>
 <center><span style="font-variant:small-caps;font-family: Times New Roman, Times, serif;"><font size="5">Segundo de Grado en Matemáticas, Curso 2020/21</font></span></center>
  <center><span style="font-variant:small-caps;font-family: Times New Roman, Times, serif;"><font size="4">Facultad de Ciencias de la Universidad de Málaga</font></span></center>

 <center><span style="font-weight: bold; font-family: Times New Roman, Times, serif;"><font size="3">Convocatoria Ordinaria de Junio. 22/06/2021</font></span></center>

In [1]:
# Cargamos los módulos necesarios
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *  # \

#### Ejercicio 1.

a) Definir una función en python llamada ```trilpbanda``` que tome como argumentos de entrada $n$ y $p$ y devuelva como salida una matriz de tamaño $n\times n$, triangular inferior y $p$-semibanda, de manera que los elementos de la diagonal sean 2 y las subdiagonales sean -1 para la primera subdiagonal, -2 para la segunda subdiagonal, y así hasta ser $-p$ la subdiagonal $p$-ésima.

In [3]:
def trilpbanda(n,p):
    A = 2*eye(n)
    for i in range(p):
        A = A - (i+1)*eye(n, k = -(i+1))
    return A
# El bucle for i in range(p) va desde 0 hasta p-1, pero como necesitamos que vaya desde 1 a p, sumamos 1 a i en cada
# iteración

b) Considerar ```A= tripanda(5,3)```, y $B=(2, 1 , -1 , -4 ,-4)^t$. Resolver el sistema $AX=B$ usando el método del ```descenso```.

In [6]:
A = trilpbanda(5,3)
B = array([[2], [1], [-1], [-4], [-4]])
exito, X = descenso(A,B)
if exito:
    print("A = ")
    print(A)
    print()
    print("B = ")
    print(B)
    print()
    print("La solución del sistema AX = B es: X")
    print(X)
    print ("Hola mi nombre es Juanma")

A = 
[[ 2.  0.  0.  0.  0.]
 [-1.  2.  0.  0.  0.]
 [-2. -1.  2.  0.  0.]
 [-3. -2. -1.  2.  0.]
 [ 0. -3. -2. -1.  2.]]

B = 
[[ 2]
 [ 1]
 [-1]
 [-4]
 [-4]]

La solución del sistema AX = B es: X
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


#### Ejercicio 2.
Consideremos la matriz 
$$A=\begin{pmatrix}
 9 & 1 & 1 & 5 \\
 1 & 10 & 1 & 9 \\
1 & 1 & 10 & 1 \\
5 & 9 & 1 & 10 
\end{pmatrix}$$

a) Analizar si esta matriz admite factorización de Cholesky, y en tal caso, resolver mediante el método de Cholesky el sistema $AX=B$ donde $B$ es el el vector $B=(16,21,13,25)^t$

In [5]:
A = array([[9,1,1,5], [1,10,1,9], [1,1,10,1], [5,9,1,10]])
B = array([[16], [21], [13], [25]])

exito, chol = metodo_cholesky(A,B)
if exito:
    print("La matriz acepta factorización de Cholesky y la solución de AX = B es: X = ")
    print(chol)

La matriz acepta factorización de Cholesky y la solución de AX = B es: X = 
[[1.]
 [1.]
 [1.]
 [1.]]


b) Se considera el sistema perturbado $\bar{A}\bar{X}=B$, donde

$$\bar{X}=X+\delta X, \qquad \bar{A}=A+\Delta A, \quad \text{siendo} \quad \Delta{A}=\verb"random.rand(4,4)/100"$$

Verificar la desigualdad 

$$\frac{\|\Delta X\|_2}{\|X+\Delta X\|_2}\leq \text{cond}_2(A) \frac{\|\Delta A\|_2}{\|A\|_2}$$
calculando todas las cantidades que aparecen en la misma.

In [10]:
# La solución del sistema ya la hemos calculado en el apartado anterior, luego X = chol 
X = chol

deltaA = random.rand(4,4)/100
A_ = A + deltaA

exito, X_ = gauss_pp(A_,B)

deltaX = X_ - X

norma_deltaX = norma_vec(X, 2)
print("Norma 2 de deltaX: ",norma_deltaX)
norma_X_ = norma_vec(X_,2)
print("Norma 2 de X_: ",norma_X_)
norma_A = norma_mat(A,2)
print("Norma 2 de A: ",norma_A)
norma_invA = norma_vec(inv(A),2)
print("Norma 2 de inv(A): ",norma_invA)
norma_deltaA = norma_mat(deltaA,2)
print("Norma 2 deltaA: ",norma_deltaA)
print()

izquierda = norma_deltaX/norma_X_
print("El miembro izquierdo de la desigualdad es: ",izquierda)
derecha = norma_A*norma_invA*norma_deltaA/norma_A
print("El miembro derecho de la desigualdad es: ",derecha)
print("La desigualdad es: ",izquierda <= derecha)

Norma 2 de deltaX:  1.999999999999776
Norma 2 de X_:  22.36683208086633
Norma 2 de A:  3.233994093357658
Norma 2 de inv(A):  1.5830896498638898
Norma 2 deltaA:  0.021443011858034624

El miembro izquierdo de la desigualdad es:  0.0894181166456144
El miembro derecho de la desigualdad es:  0.03394621013436327
La desigualdad es:  False


#### Ejercicio 3
Calcular toda la información posible sobre los autovalores y autovectores de la matriz $A$, usando el método de la potencia y sus variantes. Usar como vector inicial el vector $X_0=(1,0,0,0)^t$. Justificar las conclusiones extraídas de la información obtenida.

$$A=\begin{pmatrix}
 2& 0 & 0 & 1  \\
 0 & 1 & 0 & 1\\
0 & 0 & 3 & 1 \\
-1 & 0 & 0 &1
\end{pmatrix}$$

In [3]:
A = array([[2,0,0,1], [0,1,0,1], [0,0,3,1], [-1,0,0,1]])
X0 = array([[1], [0], [0], [0]])

print("--- Primer autovalor ---")
exito, normas, lambdas, X  = potencia(A, X0, inf, 200, 1e-8)
print()
print("\n Método de la potencia con norma inf.")
if exito:
    print("Convergencias de las normas: \n" ,normas)
    print("Convergencias de los cocientes: \n" ,lambdas)
    print("Convergencias de los vectores: \n" ,X)
print()
print('''Aplicando el método de la potencia, deducimos que 3 es el autovalor de mayor módulo de A y su
autovector asociado es X = ''')
print(X)

print()
print("--- Segundo autovalor ---")
exito, normas, lambdas, X  = potenciainv(A, X0, inf, 200, 1e-8)
print()
print("\n Método de la potencia inversa con norma inf.")
if exito:
    print("Convergencias de las normas: \n" ,normas)
    print("Convergencias de los cocientes: \n" ,lambdas)
    print("Convergencias de los vectores: \n" ,X)
print()
print('''Aplicando el método de la potencia inversa, deducimos que 1 es el autovalor de mayor módulo de inb(A),
luego 1 es el autovalor más pequeño y su autovector asociado es X = ''')
print(X)

print()
print("--- Tercer autovalor ---")
exito, normas, lambdas, X  = potenciadesinv(A, X0,1.25, inf, 200, 1e-8)
print()
print("\n Método de la potencia inversa desplazada con norma inf.")
if exito:
    print("Convergencias de las normas: \n" ,normas)
    print("Convergencias de los cocientes: \n" ,lambdas)
    print("Convergencias de los vectores: \n" ,X)
print('''Aplicando el método de la potencia inversa desplaza 1.25, deducimos que 4 es el autovalor de mayor
módulo de inv(A - 1.25*Identidad)m luego 1/4 + 1.25 = 1.5 es autovalor de A y su autovector asociado es X = ''')
print(X)

print()
print("--- Cuarto autovalor ---")
print('''Nos queda por calcular un úultimo autovalor al que denotaremos h, como sabemos, la traza(A) es la suma
de los autovalores de A por tanto:
traza(A) = 3 + 1 + 1.5 + h
h = 7 - 5.5
h = 1.5

Por tanto, los autovalores de A son 1, 1.5, 1.5 y 3
''')

--- Primer autovalor ---

 Potencia: convergencia numérica alcanzada.


 Método de la potencia con norma inf.
Convergencias de las normas: 
 2.9999491964572997
Convergencias de los cocientes: 
 [ 1.0000000e+00+0.j -5.9048000e+04+0.j  2.9999492e+00+0.j
  2.0000000e+00+0.j]
Convergencias de los vectores: 
 [[-1.69348010e-05]
 [ 1.69345142e-05]
 [-1.00000000e+00]
 [ 3.38696020e-05]]

Aplicando el método de la potencia, deducimos que 3 es el autovalor de mayor módulo de A y su
autovector asociado es X = 
[[-1.69348010e-05]
 [ 1.69345142e-05]
 [-1.00000000e+00]
 [ 3.38696020e-05]]

--- Segundo autovalor ---

 Potenciainv: convergencia numérica alcanzada.


 Método de la potencia inversa con norma inf.
Convergencias de las normas: 
 0.9999830654857665
Convergencias de los cocientes: 
 [-1.00036285e-16+0.j  9.99983065e-01+0.j -1.96826667e+04+0.j
  1.00000000e+00+0.j]
Convergencias de los vectores: 
 [[ 1.69409458e-21]
 [-1.00000000e+00]
 [ 5.64483807e-06]
 [-1.69348010e-05]]

Aplicando el mét