 <center><span style="font-variant:small-caps;font-family: Times New Roman, Times, serif;"><font size="6">Métodos Numéricos II</font></span></center>
 <center><span style="font-variant:small-caps;font-family: Times New Roman, Times, serif;"><font size="5">Segundo de Grado en Matemáticas, Curso 2020/21</font></span></center>
  <center><span style="font-variant:small-caps;font-family: Times New Roman, Times, serif;"><font size="4">Facultad de Ciencias de la Universidad de Málaga</font></span></center>

 <center><span style="font-weight: bold; font-family: Times New Roman, Times, serif;"><font size="3">Convocatoria Ordinaria de Junio. 22/06/2021</font></span></center>

In [1]:
# Cargamos los módulos necesarios
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *  # \

#### Ejercicio 1.

a) Definir una función en python llamada ```trilpbanda``` que tome como argumentos de entrada $n$ y $p$ y devuelva como salida una matriz de tamaño $n\times n$, triangular inferior y $p$-semibanda, de manera que los elementos de la diagonal sean 2 y las subdiagonales sean -1 para la primera subdiagonal, -2 para la segunda subdiagonal, y así hasta ser $-p$ la subdiagonal $p$-ésima.

In [57]:
#Ejercicio 1
print("\nEjercicio 1. Apartado ")
def trilpbanda(n, p):
    A = 2*eye(n)
    for i in range(p+1):
        A = A - i*eye(n, k = -i)
    return A    



Ejercicio 1. Apartado 
[[ 2.  0.  0.  0.  0.]
 [-1.  2.  0.  0.  0.]
 [-2. -1.  2.  0.  0.]
 [-3. -2. -1.  2.  0.]
 [ 0. -3. -2. -1.  2.]]


b) Considerar ```A= tripanda(5,3)```, y $B=(2, 1 , -1 , -4 ,-4)^t$. Resolver el sistema $AX=B$ usando el método del ```descenso```.

In [62]:
#Ejercicio 1
print("\nEjercicio 1. Apartado b)")
A = trilpbanda(5,3)
print("\nLa matriz A es:")
print(A)

B = array([[2], [1], [-1], [-4], [-4]])
print("\nEl segundo miembro del sistema AX = B es :")
print(B)

exito, X = descenso(A, B)

if exito:
    print("\nLa solución del sistema AX = B es:")
    print(X)
else:
    print("\nError:", X)


Ejercicio 1. Apartado b)

La matriz A es:
[[ 2.  0.  0.  0.  0.]
 [-1.  2.  0.  0.  0.]
 [-2. -1.  2.  0.  0.]
 [-3. -2. -1.  2.  0.]
 [ 0. -3. -2. -1.  2.]]

El segundo miembro del sistema AX = B es :
[[ 2]
 [ 1]
 [-1]
 [-4]
 [-4]]

La solución del sistema AX = B es:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


#### Ejercicio 2.
Consideremos la matriz 
$$A=\begin{pmatrix}
 9 & 1 & 1 & 5 \\
 1 & 10 & 1 & 9 \\
1 & 1 & 10 & 1 \\
5 & 9 & 1 & 10 
\end{pmatrix}$$

a) Analizar si esta matriz admite factorización de Cholesky, y en tal caso, resolver mediante el método de Cholesky el sistema $AX=B$ donde $B$ es el el vector $B=(16,21,13,25)^t$

In [6]:
#Ejercicio 2
print("\nEjercicio 2. Apartado a)")

print("\nLa matriz A es:")
A = array([[9, 1, 1, 5], [1, 10, 1, 9], [1, 1, 10, 1], [5, 9, 1, 10]])
print(A)

## Sabemos que para que la matriz admita la factorización de Cholesky, tiene que ser simétrica y A lo es.
## Tambien se tiene que tener que A sea definida positiva y se ve claramente que lo es, luego apliquemos el programa
## del método de Cholesky.

print("\nEl segundo miembro del sistema AX = B es:")
B = array([[16], [21], [13], [25]])
print(B)

## Resolvamos el sistema AX = B con el método de Cholesky que esta implementado del fichero algoritmos.

exito, X = metodo_cholesky(A, B)  ## En exito se almacena el exito de la resolución y en X la solución del sistema usando dicho método

if exito:
    print("\nLa solución es X = ")
    print(X)
else:
    print("\nError", X)


Ejercicio 2. Apartado a)

La matriz A es:
[[ 9  1  1  5]
 [ 1 10  1  9]
 [ 1  1 10  1]
 [ 5  9  1 10]]

El segundo miembro del sistema AX = B es:
[[16]
 [21]
 [13]
 [25]]

La solución es X = 
[[1.]
 [1.]
 [1.]
 [1.]]


b) Se considera el sistema perturbado $\bar{A}\bar{X}=B$, donde

$$\bar{X}=X+\delta X, \qquad \bar{A}=A+\Delta A, \quad \text{siendo} \quad \Delta{A}=\verb"random.rand(4,4)/100"$$

Verificar la desigualdad 

$$\frac{\|\Delta X\|_2}{\|X+\Delta X\|_2}\leq \text{cond}_2(A) \frac{\|\Delta A\|_2}{\|A\|_2}$$
calculando todas las cantidades que aparecen en la misma.

In [21]:
#Ejercicio 2

print("\nEjercicio 2. Apartado b)")

print("\nLa matriz dA (matriz incremento de A) es:")
random.seed(0) ## Al usar esto conseguimos que la matriz dA no cambie cada vez que corramos el programa
dA = random.rand(4,4)/100
print(dA)

## Calculemos la matriz Aper (matriz perturbada), sabiendo que Aper = A + dA
print("\nLa matriz A perturbada es:")
Aper = A - dA
print(Aper)

## Calculemos la inversa de la matriz A para calcular el condicionador_2 de A, llamemosla iA
## Para calcularla resolveremos el sistema AX=I, donde I es la identidad, mediante el método de gauss con pivot parcial

I = eye(shape(A)[0])

e, iA = gauss_pp(A, I)
print("\nLa inversa de A es:")
print(iA)

## Calculemos el condicionador_2 de A, llamemoslo cond

cond = norma_mat(A, 2)*norma_mat(iA, 2)
print("\nEl condicionador de la matriz A es cond =", cond)

## Calculemos Xper, que sabemos que es la solucion del sistema AperXper=B

e, Xper = gauss_pp(Aper, B)
print("\nLa solución del sistema perturbado es:")
print(Xper)

## Calculemos dX sabiendo que Xper = X + dX

dX = Xper - X
print("\nEl incremento de las soluciones es:")
print(dX)

## Ya tenemos caracterizados todos los elementos que estan involucrados en la desigualdad, veamos si se cumple.
## Llamemos izq al cociente de la izquierda de la desigualdad, y a los de la derecha llamemoslos der.

izq = norma_vec(dX, 2)/norma_vec(Xper, 2)

print("\nEl valor de la izquierda de la desigualdad es:", izq)

der = cond*(norma_mat(dA, 2)/norma_mat(A, 2))
print("\nEl valor de la derecha de la desigualdad es:", der)

if izq <= der :
    print("\nLa desigualdad se cumple")
else:
    print("\nLa desigualdad no se cumple")


Ejercicio 2. Apartado b)

La matriz dA (matriz incremento de A) es:
[[0.00548814 0.00715189 0.00602763 0.00544883]
 [0.00423655 0.00645894 0.00437587 0.00891773]
 [0.00963663 0.00383442 0.00791725 0.00528895]
 [0.00568045 0.00925597 0.00071036 0.00087129]]

La matriz A perturbada es:
[[8.99451186 0.99284811 0.99397237 4.99455117]
 [0.99576345 9.99354106 0.99562413 8.99108227]
 [0.99036337 0.99616558 9.99208275 0.99471105]
 [4.99431955 8.99074403 0.99928964 9.99912871]]

La inversa de A es:
[[ 188.  347.  -13. -405.]
 [ 347.  641.  -24. -748.]
 [ -13.  -24.    1.   28.]
 [-405. -748.   28.  873.]]

El condicionador de la matriz A es cond = 35528.59048197497

La solución del sistema perturbado es:
[[ 1.61948039]
 [ 2.1408808 ]
 [ 0.95988915]
 [-0.32958083]]

El incremento de las soluciones es:
[[ 0.61948039]
 [ 1.1408808 ]
 [-0.04011085]
 [-1.32958083]]

El valor de la izquierda de la desigualdad es: 0.6476615670710898

El valor de la derecha de la desigualdad es: 39.57899407083189

La 

#### Ejercicio 3
Calcular toda la información posible sobre los autovalores y autovectores de la matriz $A$, usando el método de la potencia y sus variantes. Usar como vector inicial el vector $X_0=(1,0,0,0)^t$. Justificar las conclusiones extraídas de la información obtenida.

$$A=\begin{pmatrix}
 2& 0 & 0 & 1  \\
 0 & 1 & 0 & 1\\
0 & 0 & 3 & 1 \\
-1 & 0 & 0 &1
\end{pmatrix}$$

In [47]:
# Ejercicio 3
print("\nEjercicio 3")
print("\nLa matriz A es:")
A = array([[2, 0, 0, 1], [0, 1, 0, 1], [0, 0, 3, 1], [-1, 0, 0, 1]])
print(A)

print("\nEl vector inicial X0 es:")
X0 = array([[1], [0], [0], [0]])
print(X0)

## Comencemos usando el método de la potencia
print("\n-------------------------Potencia-----------------------\n")
exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 3 + 0j es autovalor de A")

## Usemos ahora el método de la potencia inversa
print("\n-------------------------Potencia Inversa-----------------------\n")
exito, normas, lambdas, X = potenciainv(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe lo que deducimos que 1/(1+0j) es autovalor de la inv(A), luego 1+0j es autovalor de A.")

print("\n-------------------------Potencia Con Desplazamiento con 0+0.5j-----------------------\n")
exito, normas, lambdas, X = potenciades(A, X0, 0+0.5j, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 1.5-0.8660254j es autovalor de A, ya que la convergencia de los cocientes con el método")
print("de la potencia desplazado, es 1.5-1.3660254j, luego restandole el desplazamiento tenemos el 1.5-0.8660254j.")

print("\n-------------------------Potencia Con Desplazamiento con 0-0.5j-----------------------\n")
exito, normas, lambdas, X = potenciades(A, X0, 0-0.5j, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 1.5+0.8660254j es autovalor de A, ya que la convergencia de los cocientes con el método")
print("de la potencia desplazado, es 1.5+1.3660254j, luego restandole el desplazamiento tenemos el 1.5+0.8660254j.")

print("\nPor tanto tenemos que los autovalores de A son el 1+0j, el 3+0j, el 1.5+0.8660254j y el 1.5-0.8660254j")
print("\nVeamos que efectivamente coinciden con los autovalores de A (esta vez calculados con el comando eig)")
print(eig(A)[0])



Ejercicio 3

La matriz A es:
[[ 2  0  0  1]
 [ 0  1  0  1]
 [ 0  0  3  1]
 [-1  0  0  1]]

El vector inicial X0 es:
[[1]
 [0]
 [0]
 [0]]

-------------------------Potencia-----------------------


 Potencia: convergencia numérica alcanzada.

Convergencia de las normas:
3.000000002581175

Convergencia de los cocientes:
[1.+0.j 0.+0.j 3.+0.j 2.+0.j]

convergencia de los vectores:
[[ 8.60391598e-10]
 [-8.60391599e-10]
 [-1.00000000e+00]
 [-1.72078320e-09]]

De aqui deducimos que 3 + 0j es autovalor de A

-------------------------Potencia Inversa-----------------------


 Potenciainv: convergencia numérica alcanzada.

Convergencia de las normas:
0.999999976769428

Convergencia de los cocientes:
[-0.        +0.j  0.99999998+0.j  0.        +0.j  1.        +0.j]

convergencia de los vectores:
[[ 0.00000000e+00]
 [-1.00000000e+00]
 [ 7.74352402e-09]
 [-2.32305726e-08]]

De lo que deducimos que 1/(1+0j) es autovalor de la inv(A), luego 1+0j es autovalor de A.

-------------------------Potencia