In [1]:
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *

**Ejercicio 1.**
Utilizando el método de la potencia y sus variantes, calcular toda la información posible sobre los autovalores y autovectores de la matriz:

$$A=\begin{pmatrix}
  8 & -8 & 0 & 4 & 4\\
 16 & 0 & -8 & -4 & -4\\
 18 & -14 & 2 & -2 & -2\\
 19 & -13 & -5 & 3 & -1\\
 19 & -13 & -5 & -1 & 3
\end{pmatrix}
\quad$$

Se valorará positivamente una respuesta estructurada en la forma: método utilizado, vector inicial, norma utilizada,
conclusiones.

In [3]:
print("\nEjercicio 1")

A = array([[8, -8, 0, 4, 4], [16, 0, -8, -4, -4], [18, -14, 2, -2, -2], [19, -13, -5, 3, -1], [19, -13, -5, -1, 3]])

# print(eig(A)[0])    [-16.  16.   4.   8.   4.]

print("\nLa matriz A es:")
print(A)

X0 = array([[1], [0], [1], [0], [1]])

print("\nEl vector inicial va a ser:")
print(X0, "\n")
print(norm(X0))

#Método de la potencia
print("\n-------------------------Potencia-----------------------\n")
exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 4 es autovalor de A")

#Método de la potencia inversa
print("\n-------------------------Potencia Inversa-----------------------\n")
exito, normas, lambdas, X = potenciainv(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe lo que deducimos que 1/4 es autovalor de la inv(A), luego 4 es autovalor de A.")

#Método de la potencia con desplazamiento
print("\n-------------------------Potencia Con Desplazamiento 10-----------------------\n")
exito, normas, lambdas, X = potenciades(A, X0, 10, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que -16 es autovalor de A, ya que la convergencia de los cocientes con el método")
print("de la potencia desplazado, es -6, luego restandole y sumandole el desplazamiento tenemos el -16.")

#Método de la potencia inversa con desplazamiento
print("\n-------------------------Potencia Inversa Con Desplazamiento 7-----------------------\n")
exito, normas, lambdas, X = potenciadesinv(A, X0, 7, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 8 es autovalor de A, ya que la convergencia de los cocientes con el método de la potencia inversa")
print("con desplazamiento 7 es 1/1, luego sumandole el desplazamiento tenemos el 8.")

print("\n-------------------------Potencia Inversa Con Desplazamiento 13-----------------------\n")
exito, normas, lambdas, X = potenciadesinv(A, X0, 13, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 16 es autovalor de A, ya que la convergencia de los cocientes con el método de la potencia inversa")
print("con desplazamiento 13 es 1/3, luego sumandole el desplazamiento tenemos el 16.")

print("\nLuego los autovalores de la matriz A son el 16, el -16, el 4 y el 8")

print("\nLos autovalores de la matriz A con la herramienta eig son:")
print(eig(A)[0])


Ejercicio 1

La matriz A es:
[[  8  -8   0   4   4]
 [ 16   0  -8  -4  -4]
 [ 18 -14   2  -2  -2]
 [ 19 -13  -5   3  -1]
 [ 19 -13  -5  -1   3]]

El vector inicial va a ser:
[[1]
 [0]
 [1]
 [0]
 [1]] 

1.7320508075688772

-------------------------Potencia-----------------------

ERROR potencia: no se alcanza convergencia.

De aqui deducimos que 4 es autovalor de A

-------------------------Potencia Inversa-----------------------


 Potenciainv: convergencia numérica alcanzada.

Convergencia de las normas:
0.25000000000000056

Convergencia de los cocientes:
[0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j]

convergencia de los vectores:
[[ 0.66666667]
 [ 0.66666667]
 [ 0.66666667]
 [-0.33333333]
 [ 1.        ]]

De lo que deducimos que 1/4 es autovalor de la inv(A), luego 4 es autovalor de A.

-------------------------Potencia Con Desplazamiento 10-----------------------


 Potencia: convergencia numérica alcanzada.

Convergencia de las normas:
26.0

Convergencia de los cocientes:
[  0.+0

-----

**Ejercicio 2.** 
Dada la matriz A del ejercicio anterior, se considera también

$$B=\begin{pmatrix}
8\\
0\\
2\\
3\\
3
\end{pmatrix}
\quad \text{y} 
\quad \bar{B}=\begin{pmatrix}
8.5 \\
-0.5\\
2.5\\
2.5\\
3.5
\end{pmatrix}
$$

Resolver (por el método que se quiera) el sistema lineal $AX=B$, así como el sistema perturbado $A\bar{X}=\bar{B}$. Posteriormente hacer el análisis numérico de esta perturbación de los datos, comprobando que se verifica el resultado (se puede utilizar la norma que se desee):

$$\frac{\|\delta X\|}{\|X\|}\leq \text{cond}(A) \frac{\|\delta B\|}{\|B\|}$$

Se valorará positivamente una respuesta estructurada en la forma: cálculos a realizar, identificación de todas las cantidades
que aparecen, comandos/programas utilizados, resultado final.

In [55]:
print("\nEjercicio 2")

print("\nEl segundo miembro del sistema es B:")
B = array([[8], [0], [2], [3], [3]])
print(B)

print("\nEl segundo miembro del sistema perturbado es Bper:")
Bper = array([[8.5], [-0.5], [2.5], [2.5], [3.5]])
print(Bper)

##Calculemos el condicionamiento de A

cond = norma_mat(A, inf)*norma_mat(inv(A), inf)
print("\nEl condicionamiento de A es cond =", cond)

##Calculemos dB sabiendo que Bper = B + dB

dB = Bper - B

print("\nEl incremento del segundo miembro es dB:")
print(dB)

##Calculemos la solucion del sistema AX = B mediante el método de gaus_pp

e, X = gauss_pp(A, B)

print("\nLa solución del sistema AX = B es:")
print(X1)

##Calculemos la solucion del sistema AX = B mecond = norma_mat(A, 2)*norma_mat(iA, 2)diante el método de gaus_pp

e, Xper = gauss_pp(A, Bper)

print("\nLa solución del sistema AXper = Bper es:")
print(Xper)

##Calculemos dX sabiendo que Xper = X + dX

dX = Xper - X

print("\nEl incremento de las soluciones es:")
print(dX)

print("\nYa tenemos caracterizados todos los elementos de las desigualdades, ahora veamos si se prueba la desigualdad.")

##Llamaremos izq a los elementos de la izquierda de la desigualdad.

izq = norma_vec(dX, inf)/norma_vec(X, inf)

##Llamaremos der a los elementos de la derecha de la desigualdad.

der = cond*(norma_vec(dB, inf)/norma_vec(B, inf))

if (izq <= der):
    print("\nLa desigualdad si se cumple.")
else:
    print("\nLa desigualdad no se cumple.")


Ejercicio 2

El segundo miembro del sistema es B:
[[8]
 [0]
 [2]
 [3]
 [3]]

El segundo miembro del sistema perturbado es Bper:
[[ 8.5]
 [-0.5]
 [ 2.5]
 [ 2.5]
 [ 3.5]]

El condicionamiento de A es cond = 25.625

El incremento del segundo miembro es dB:
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]
 [ 0.5]]

La solución del sistema AX = B es:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

La solución del sistema AXper = Bper es:
[[1.0546875]
 [1.0390625]
 [1.125    ]
 [0.921875 ]
 [1.171875 ]]

El incremento de las soluciones es:
[[ 0.0546875]
 [ 0.0390625]
 [ 0.125    ]
 [-0.078125 ]
 [ 0.171875 ]]

Ya tenemos caracterizados todos los elementos de las desigualdades, ahora veamos si se prueba la desigualdad.

La desigualdad si se cumple.


-----