In [1]:
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *

Se considera el sistema lineal $AX = B$, donde

$$A=\begin{pmatrix}
 1 & 2 & 3 & 4 \\
 2 & 9 & 12 & 15 \\
3 & 26 & 41 & 49 \\
5 & 40 & 107 & 135 
\end{pmatrix}$$

$$B=\begin{pmatrix}
 20 \\
 74 \\
 221 \\
489 
\end{pmatrix}$$

1. Calcular el sistema lineal dado

In [28]:
A = array([[1, 2, 3, 4], [2, 9, 12, 15], [3, 26, 41, 49], [5, 40, 107, 135]])
print("A: ")
print(A)
B = array([[20], [74], [221], [489]])
print("B: ")
print(B)

exito, X = gaussjordan_1p(A, B)

if exito:
    print("La solucion es X:")
    print(X)

A: 
[[  1   2   3   4]
 [  2   9  12  15]
 [  3  26  41  49]
 [  5  40 107 135]]
B: 
[[ 20]
 [ 74]
 [221]
 [489]]
La solucion es X:
[[4.]
 [3.]
 [2.]
 [1.]]


2. Calcular la inversa de esta matriz

In [29]:
print("La inversa de A es: ")
print(inv(A))

print("\n Usando el Metodo de Gauus, con B= I, la inversa de A es: ")
I = eye(shape(A)[0])
exito, A_ = gaussjordan_pp(A, I)
if exito: 
    print(A_)

La inversa de A es: 
[[ 2.895  -1.255   0.2925 -0.0525]
 [-1.01    0.69   -0.115  -0.005 ]
 [ 3.775  -2.975   0.9125 -0.1125]
 [-2.8     2.2    -0.7     0.1   ]]

 Usando el Metodo de Gauus, con B= I, la inversa de A es: 
[[ 2.895  -1.255   0.2925 -0.0525]
 [-1.01    0.69   -0.115  -0.005 ]
 [ 3.775  -2.975   0.9125 -0.1125]
 [-2.8     2.2    -0.7     0.1   ]]


3. Calcular, si existen, las matrices L y U de la factorización LU de la matriz A.  

In [30]:
exito, lu = facto_lu(A)

if exito:
    print("La factorizacion LU existe")
    L = tril(lu, k = -1) + eye(shape(A)[0])
    U = triu(lu)
    print("La matriz L es: ")
    print(L)
    print("La matriz U es: ")
    print(U)

La factorizacion LU existe
La matriz L es: 
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 4. 1. 0.]
 [5. 6. 7. 1.]]
La matriz U es: 
[[ 1.  2.  3.  4.]
 [ 0.  5.  6.  7.]
 [ 0.  0.  8.  9.]
 [ 0.  0.  0. 10.]]


4. Calcular, si existe, la matriz C de la factorización de Cholescky de la matriz A.

In [31]:
exito, c = facto_cholesky(A)
if exito:
    print("La matriz del metodo Cholescky es: ")
    print(tril(c))

La matriz del metodo Cholescky es: 
[[1.         0.         0.         0.        ]
 [2.         2.23606798 0.         0.        ]
 [3.         2.68328157 4.97995984 0.        ]
 [4.         3.13049517 5.7430182  8.73027731]]


5. Utilizar el metodo de la potencia (o alguna de sus variantes) para calcular el autovalor de modulo mayor de A.

In [33]:
#Método de la potencia
print(eig(A)[0])
X0 = array([[0], [1],[0],[0]])
print("\n-------------------------Potencia-----------------------\n")
exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 179.85167083 es autovalor de A")

[179.85167083+0.j           0.25541588+0.j
   2.94645664+0.16117144j   2.94645664-0.16117144j]

-------------------------Potencia-----------------------


 Potencia: convergencia numérica alcanzada.

Convergencia de las normas:
179.85167083374157

Convergencia de los cocientes:
[179.85167083+0.j 179.85167083+0.j 179.85167083+0.j 179.85167083+0.j]

convergencia de los vectores:
[[0.02993487]
 [0.11448298]
 [0.37497829]
 [1.        ]]

De aqui deducimos que 1040.91 es autovalor de A


6. Utilizar el metodo de la potencia (o alguna de sus variantes) para calcular el autovalor de modulo menor de A.

In [38]:
print("\n-------------------------Potencia Inversa-----------------------\n")
exito, normas, lambdas, X = potenciainv(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 3.91518337 es autovalor de inv(A), luego ", 1/3.91518337, "es autovalor de A")
print("Por ahora tenemos que 179.85167083 el autovalor mayor y que ", 1/3.91518337, " es el menor, luego dentro de ese rango se encuentran los demas")


-------------------------Potencia Inversa-----------------------


 Potenciainv: convergencia numérica alcanzada.

Convergencia de las normas:
3.915183374039974

Convergencia de los cocientes:
[3.91518337+0.j 3.91518337+0.j 3.91518337+0.j 3.91518337+0.j]

convergencia de los vectores:
[[-0.59822576]
 [ 0.22183415]
 [-1.        ]
 [ 0.75044027]]

De aqui deducimos que 3.91518337 es autovalor de inv(A), luego  0.2554158785160553 es autovalor de A
Por ahora tenemos que 179.85167083 el autovalor mayor y que  0.2554158785160553  es el menor, luego dentro de ese rango se encuentran los demas


7. Calcular $||A||_1$, $||A||_2$, $||A||_\infty$

In [39]:
print("La norma 1 de A es: ", norma_mat(A, 1))
print("La norma 2 de A es: ", norma_mat(A, 2))
print("La norma inf de A es: ", norma_mat(A, inf))

La norma 1 de A es:  203.0
La norma 2 de A es:  190.8524857443097
La norma inf de A es:  287.0


8. Calcular el $cond_1(A)$, $cond_2(A)$, $cond_\infty(A)$

In [41]:
A_ = inv(A)
print("El cond1(A) = ", norma_mat(A, 1)*norma_mat(A_, 1))
print("El cond2(A) = ", norma_mat(A, 2)*norma_mat(A_, 2))
print("El condInf(A) = ", norma_mat(A, inf)*norma_mat(A_, inf))

El cond1(A) =  2127.4399999999523
El cond2(A) =  1323.4641434701864
El condInf(A) =  2231.4249999999424


9. Utilizando el metodo de la potencia y sus variantes, calcular toda la información posible sobre los autovalores y autovectores de: 

$$A=\begin{pmatrix}
 8 & -8 & 0 & 4 & 4 \\
 16 & 0 & -8 & -4 & -4 \\
18 & -14 & 2 & -2 & -2 \\
19 & -13 & -5 & 3 & -1 \\
19 & -13 & -5 & -1 & 3 \\ 
\end{pmatrix}$$

In [57]:
A = array([[8, -8, 0, 4, -4], [16, 0, -8, -4, -4], [18, -14, 2, -2, -2], [19, -13, -5, 3, -1], [19, -13, -5, -1, 3]])
print(eig(A)[0])
X0 = array([[0], [0],[1],[0],[0]])
print("\n-------------------------Potencia-----------------------\n")
exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos que 14.46565184 es autovalor de A, y además, es el de mayor modulo")

#X0 = array([[1], [1],[1],[1],[1]])
print("\n-------------------------Potencia inversa-----------------------\n")
exito, normas, lambdas, X = potenciainv(A, X0, inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui no deducimos nada")

print("\n-------------------------Potencia inversa-----------------------\n")
exito, normas, lambdas, X = potenciades(A, X0,-4.47849475 +1.32j,  inf, 200, 1e-15)

if exito:
    print("\nConvergencia de las normas:")
    print(normas)
    print("\nConvergencia de los cocientes:")
    print(lambdas)
    print("\nconvergencia de los vectores:")
    print(X)
else:
    print(normas)

print("\nDe aqui deducimos",  1/(18.94414659 + 1.32j) -4.47849475,   " es autovalor de A")

[-4.47849475+1.32408048j -4.47849475-1.32408048j 14.46565184+0.j
  6.49133766+0.j          4.        +0.j        ]

-------------------------Potencia-----------------------


 Potencia: convergencia numérica alcanzada.

Convergencia de las normas:
14.465651839391601

Convergencia de los cocientes:
[14.46565184+0.j 14.46565184+0.j 14.46565184+0.j 14.46565184+0.j
 14.46565184+0.j]

convergencia de los vectores:
[[ 0.54725593]
 [-0.44229579]
 [ 1.        ]
 [ 0.89427396]
 [ 0.89427396]]

De aqui deducimos que 14.46565184 es autovalor de A, y además, es el de mayor modulo

-------------------------Potencia inversa-----------------------

ERROR potenciainv: no se alcanza convergencia.

De aqui no deducimos nada

-------------------------Potencia inversa-----------------------


 Potencia: convergencia numérica alcanzada.

Convergencia de las normas:
18.990078725491312

Convergencia de los cocientes:
[18.94414659-1.32j 18.94414659-1.32j 18.94414659-1.32j 18.94414659-1.32j
 18.94414659-1.32j]