In [1]:
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min
from algoritmos import *

**Ejercicio 1.**
Se considera el sistema lineal $AX=B$, donde:

$$A=\begin{pmatrix}
10 & 1 & 4 & 0\\
1 & 10 & 5 & -1\\
4 & 5 & 10 & 7\\
0 & -1 & 7 & 9 
\end{pmatrix}
\quad \text{y} \quad
B=\begin{pmatrix}
15 \\
15\\
26\\
15
\end{pmatrix}$$

**a)**
Al aplicar el método de Gauss con estrategia de pívot parcial al sistema anterior, se obtiene un sistema triangular
superior equivalente, que posteriormente se resuelve mediante un proceso de remonte. Escribir dicho sistema
triangular superior y la solución del sistema.

In [13]:
#Apartado a

print("\nEjercicio 1")
print("\nPrimero hagamos el programa que vamos a necesitar para para que nos devuelvan la matriz MA y la matriz MB que dan")
print("\nlugar al sistema triangular superior.")

def gauss_pp_ejer1(A, B):
    (m, n) = shape(A)
    (p, q) = shape(B)
    if m != n or n != p or q < 1:
        return False, "gauss_pp: error en las dimensiones"
    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)
    for k in range(n-1):
        pos = argmax(abs(gaussA[k:n, k]))
        ik = pos+k
        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]
        if abs(gaussA[k, k]) >= 1e-15:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] = gaussA[i, k+1:]-gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] = gaussB[i, :]-gaussA[i, k]*gaussB[k, :]
    return gaussA, gaussB

print("\nLa matriz A es:")
A = array([[10, 1, 4, 0], [1, 10, 5, -1], [4, 5, 10, 7], [0, -1, 7, 9]])
print(A)

print("\nEl segundo miembro es:")
B = array([[15], [15], [26], [15]])
print(B)


a, b = gauss_pp_ejer1(A, B)

print("\nLa matriz MA del sistema triangular superior equivaliente es:")
print(triu(a))

print("\nLa matriz MB del sistema triangular superior equivaliente es:")
print(b)

##Ahora resolvamos el sistema.
exito, X = gauss_pp(A, B)

print("\nLa solución del sistema AX = B es:")
print(X)



Ejercicio 1

Primero hagamos el programa que vamos a necesitar para para que nos devuelvan la matriz MA y la matriz MB que dan

lugar al sistema triangular superior.

La matriz A es:
[[10  1  4  0]
 [ 1 10  5 -1]
 [ 4  5 10  7]
 [ 0 -1  7  9]]

El segundo miembro es:
[[15]
 [15]
 [26]
 [15]]

La matriz MA del sistema triangular superior equivaliente es:
[[ 1.00000000e+01  1.00000000e+00  4.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  9.90000000e+00  4.60000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.46464646e+00  8.89898990e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.35317997e-03]]

La matriz MB del sistema triangular superior equivaliente es:
[[ 1.50000000e+01]
 [ 1.35000000e+01]
 [ 1.63636364e+01]
 [-1.35317997e-03]]

La solución del sistema AX = B es:
[[1.]
 [1.]
 [1.]
 [1.]]


---

**b)**
Calcular la inversa de A mediante el método de Gauss con estrategia de pívot parcial.

In [9]:
#Apartado b
I = eye(shape(A)[0])
print("\nCalculamos la inversa de A sabiendo que es la solucion del sistema AX=I:")
e, X= gaussjordan_pp(A,I)

print(X)



Calculamos la inversa de A sabiendo que es la solucion del sistema AX=I:
[[ 105.  167. -304.  255.]
 [ 167.  266. -484.  406.]
 [-304. -484.  881. -739.]
 [ 255.  406. -739.  620.]]


-----

**c)**
Escribir, si es posible, la factorización LU de la matriz A.

In [14]:
#Apartado c
print("\nEjercicio 3")
exito, LU = facto_lu(A)

print("\nLa matriz L de la factorización LU es:")
print(tril(LU, k=-1) + eye(shape(A)[0]))

print("\nLa matriz U de la factorización LU es:")
print(triu(LU))


Ejercicio 3

La matriz L de la factorización LU es:
[[ 1.          0.          0.          0.        ]
 [ 0.1         1.          0.          0.        ]
 [ 0.4         0.46464646  1.          0.        ]
 [ 0.         -0.1010101   1.19193548  1.        ]]

La matriz U de la factorización LU es:
[[ 1.00000000e+01  1.00000000e+00  4.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  9.90000000e+00  4.60000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  6.26262626e+00  7.46464646e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.61290323e-03]]


----

**d)**
Se considera ahora el sistema perturbado $A\bar{X}=\bar{B}$, donde $\bar{X}= X +δX$ y $\bar{B}= B +δB$ , siendo $δB=(1  1  −1  1)^t$.
Calcular la solución del sistema perturbado y hacer el análisis numérico (en norma 2) de la situación propuesta,
comprobando que el error relativo de la solución es menor o igual que el producto del condicionamiento por el
error relativo de los datos.

Es decir resolvamos la siguiente desigualdad:

$$\frac{\|\delta X\|_2}{\|X\|_2}\leq \text{cond}_2(A) \frac{\|\delta B\|_2}{\|B\|_2}$$

In [23]:
#Apartado d
print("\nApartado d")
print("\nLa matriz A es:")
A = array([[10, 1, 4, 0], [1, 10, 5, -1], [4, 5, 10, 7], [0, -1, 7, 9]])
print(A)

print("\nEl segundo miembro es:")
B = array([[15], [15], [26], [15]])
print(B)

print("\nLa matriz identidad es:")
I = eye(shape(A)[0])
print(I)

print("\nLa diferencia del segundo miembro dB es:")
dB = array([[1], [1], [-1], [1]])
print(dB)

##Calculamos Bper sabiendo que Bper = B + dB

print("\nEl segundo miembro del sistema perturbado es:")
Bper = B + dB
print(Bper)


##Calculemos la solucion del sistema AX=B
print("\nLa solución del sistema AX = B es:")
e, X = gauss_pp(A, B)
print(X)

##Calculemos la solucion del sistema perturbado AXper=Bper
print("\nLa solución del sistema AX = B es:")
e, Xper = gauss_pp(A, Bper)
print(Xper)

##Calculemos la inversa de A
e, iA = gauss_pp(A, I)
print("\nLa inversa de A es:")
print(iA)

##Calculemos el condicionamiento_2 de A
print("\nEl condicionamiento de la matriz A es:")
cond = norma_mat(A, 2)*norma_mat(iA, 2)
print(cond)

##Calculemos dX sabiendo que Xper = X + dX

dX = Xper - X

print("\nEl incremento de las soluciones es:")
print(dX)

print("\nYa tenemos caracterizados todos los elementos de las desigualdades, ahora veamos si se prueba la desigualdad.")

##Llamaremos izq a los elementos de la izquierda de la desigualdad.

izq = norma_vec(dX, 2)/norma_vec(X, 2)

##Llamaremos der a los elementos de la derecha de la desigualdad.

der = cond*(norma_vec(dB, 2)/norma_vec(B, 2))

if (izq <= der):
    print("\nLa desigualdad si se cumple.")
else:
    print("\nLa desigualdad no se cumple.")


Apartado d

La matriz A es:
[[10  1  4  0]
 [ 1 10  5 -1]
 [ 4  5 10  7]
 [ 0 -1  7  9]]

El segundo miembro es:
[[15]
 [15]
 [26]
 [15]]

La matriz identidad es:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

La diferencia del segundo miembro dB es:
[[ 1]
 [ 1]
 [-1]
 [ 1]]

El segundo miembro del sistema perturbado es:
[[16]
 [16]
 [25]
 [16]]

La solución del sistema AX = B es:
[[1.]
 [1.]
 [1.]
 [1.]]

La solución del sistema AX = B es:
[[  832.]
 [ 1324.]
 [-2407.]
 [ 2021.]]

La inversa de A es:
[[ 105.  167. -304.  255.]
 [ 167.  266. -484.  406.]
 [-304. -484.  881. -739.]
 [ 255.  406. -739.  620.]]

El condicionamiento de la matriz A es:
35792.397628802224

El incremento de las soluciones es:
[[  831.]
 [ 1323.]
 [-2408.]
 [ 2020.]]

Ya tenemos caracterizados todos los elementos de las desigualdades, ahora veamos si se prueba la desigualdad.

La desigualdad si se cumple.


----